/**
 * Utility functions exports for the API endpoint decorator.
 *
 * This module provides helper functions for merging options,
 * parsing paths, and auto-generating documentation.
 */

export { mergeOptions, mergeWithDefaults } from './merge-options.util';
export { parsePath, pathToCacheKey, generateOperationId, extractTags } from './path-parser.util';
export {
  autoGenerateDocs,
  generateSummary,
  enhanceDocsWithPreset,
} from './auto-generate-docs.util';
export {
  validateRouteOptions,
  validateCacheConfig,
  validateThrottleConfig,
  RouteOptionsValidationError,
} from './validate-options.util';
