/**
 * API Endpoint Decorator - Main Export Module
 *
 * A comprehensive decorator for defining API endpoints in NestJS applications.
 * Combines routing, authentication, caching, documentation, and more into a
 * single, powerful decorator.
 *
 * @example
 * ```typescript
 * import { Route, HttpMethod } from './decorators/api-endpoint';
 *
 * @Route({
 *   method: HttpMethod.GET,
 *   path: '/users',
 *   auth: { bearer: true },
 *   cache: { enabled: true, ttl: 300 }
 * })
 * async getUsers() {
 *   return this.userService.findAll();
 * }
 * ```
 */

// Main decorator
export { Route } from './route.decorator';

// Enums
export { HttpMethod, EndpointPreset } from './enums';

// Interfaces
export type {
  RouteOptions,
  AuthOptions,
  ResponseOptions,
  CacheConfig,
  CorsOptions,
  SecurityOptions,
  TelemetryOptions,
  CircuitBreakerOptions,
  RetryOptions,
  ThrottleOptions,
  FileUploadOptions,
  ParsedPath,
} from './interfaces';

// Constants
export {
  DEFAULT_CONSUMES,
  DEFAULT_PRODUCES,
  DEFAULT_RESPONSE_HEADERS,
  DEFAULT_API_RESPONSE_HEADERS,
  DEFAULT_REQUEST_HEADERS,
  DEFAULT_RESPONSES,
  DEFAULT_CACHE_TTL,
  DEFAULT_CORS,
  DEFAULT_RATE_LIMIT,
  DEFAULT_CIRCUIT_BREAKER,
  DEFAULT_RETRY_POLICY,
  DEFAULT_THROTTLE,
} from './constants';

// Presets
export {
  CRUD_LIST_PRESET,
  CRUD_READ_PRESET,
  CRUD_CREATE_PRESET,
  CRUD_UPDATE_PRESET,
  CRUD_DELETE_PRESET,
  CRUD_PATCH_PRESET,
  HEALTH_PRESET,
  UPLOAD_PRESET,
  DOWNLOAD_PRESET,
  applyPreset,
  hasPreset,
  getAvailablePresets,
} from './presets';

// Utilities
export {
  mergeOptions,
  mergeWithDefaults,
  parsePath,
  pathToCacheKey,
  generateOperationId,
  extractTags,
  autoGenerateDocs,
  generateSummary,
  enhanceDocsWithPreset,
} from './utils';

// Builders (for advanced usage)
export {
  buildHttpMethodDecorator,
  isValidHttpMethod,
  getValidHttpMethods,
  buildApiOperation,
  buildApiParams,
  buildApiQueries,
  buildApiBody,
  buildApiHeaders,
  buildApiConsumes,
  buildApiProduces,
  buildApiExtensions,
  buildApiTags,
  buildApiExclude,
  buildAuthDecorators,
  buildBearerAuth,
  buildApiKeyAuth,
  buildCookieAuth,
  buildBasicAuth,
  buildOAuth2Auth,
  buildResponseDecorators,
  buildOkResponse,
  buildCreatedResponse,
  buildAcceptedResponse,
  buildNoContentResponse,
  buildMovedPermanentlyResponse,
  buildFoundResponse,
  buildBadRequestResponse,
  buildUnauthorizedResponse,
  buildForbiddenResponse,
  buildNotFoundResponse,
  buildConflictResponse,
  buildUnprocessableEntityResponse,
  buildTooManyRequestsResponse,
  buildInternalErrorResponse,
  buildBadGatewayResponse,
  buildServiceUnavailableResponse,
  buildGatewayTimeoutResponse,
  buildDefaultResponse,
  buildCustomResponses,
} from './builders';
