import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';
import { randomUUID } from 'crypto';

/**
 * Request ID Middleware
 *
 * Generates a unique ID for each incoming request. This ID is used for
 * request tracking, logging, debugging, and correlating logs across services.
 *
 * @description
 * This middleware:
 * - Generates a unique UUID v4 for each request
 * - Adds X-Request-ID header to response
 * - Stores request ID in request object for use in controllers/services
 * - Preserves existing request ID if provided by client
 * - Essential for distributed tracing and log aggregation
 *
 * @features
 * - UUID v4 generation (cryptographically random)
 * - Preserves client-provided request IDs
 * - Adds request ID to response headers
 * - Accessible throughout request lifecycle
 * - Integration with logging systems
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(RequestIdMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 *
 * @example Accessing request ID in controllers
 * ```typescript
 * @Get()
 * async findAll(@Req() req: Request) {
 *   const requestId = req.headers['x-request-id'];
 *   this.logger.log(`Processing request ${requestId}`);
 *   // ...
 * }
 * ```
 *
 * @example Response headers
 * ```
 * HTTP/1.1 200 OK
 * X-Request-ID: 550e8400-e29b-41d4-a716-446655440000
 * Content-Type: application/json
 * ```
 *
 * @see https://datatracker.ietf.org/doc/html/rfc4122
 */
@Injectable()
export class RequestIdMiddleware implements NestMiddleware {
  /**
   * Header name for request ID
   *
   * @private
   */
  private readonly headerName = 'X-Request-ID';

  /**
   * Generate or preserve request ID
   *
   * @param req - Express request object
   * @param res - Express response object
   * @param next - Next function to call
   */
  use(req: Request, res: Response, next: NextFunction): void {
    // Check if client provided a request ID
    // This allows request tracing across multiple services
    let requestId = req.headers[this.headerName.toLowerCase()] as string;

    // If no request ID provided, generate a new one
    if (!requestId) {
      requestId = this.generateRequestId();
    }

    // Store request ID in request object for later access
    // This allows controllers and services to access the request ID
    req.headers[this.headerName.toLowerCase()] = requestId;

    // Add request ID to response headers
    // This allows clients to reference the request ID for support/debugging
    res.setHeader(this.headerName, requestId);

    next();
  }

  /**
   * Generate a unique request ID
   * Uses UUID v4 for cryptographically random IDs
   *
   * @returns Unique request ID
   * @private
   */
  private generateRequestId(): string {
    // Generate UUID v4 (random UUID)
    // Format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
    return `req-${randomUUID()}`;
  }
}
