import { Command, CommandRunner } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Migrate Status Command
 *
 * Shows the status of all migrations (executed and pending).
 * Similar to Laravel's `php artisan migrate:status`.
 *
 * @description CLI command for checking migration status
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Show migration status
 * npm run console migrate:status
 * ```
 */
@Injectable()
@Command({
  name: 'migrate:status',
  description: 'Show the status of each migration',
})
export class MigrateStatusCommand extends CommandRunner {
  private readonly logger = new Logger(MigrateStatusCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  async run(): Promise<void> {
    try {
      const migrator = this.orm.getMigrator();

      this.logger.log('Migration Status:\n');

      // Get executed and pending migrations
      const executed = await migrator.getExecutedMigrations();
      const pending = await migrator.getPendingMigrations();

      // Display executed migrations
      if (executed.length > 0) {
        this.logger.log('✅ Executed Migrations:');
        executed.forEach((migration) => {
          const executedAt = migration.executed_at
            ? new Date(migration.executed_at).toLocaleString()
            : 'Unknown';
          this.logger.log(`  ✓ ${migration.name} (executed at: ${executedAt})`);
        });
      } else {
        this.logger.log('✅ Executed Migrations: None');
      }

      this.logger.log('');

      // Display pending migrations
      if (pending.length > 0) {
        this.logger.log('⏳ Pending Migrations:');
        pending.forEach((migration) => {
          this.logger.log(`  • ${migration.name}`);
        });
      } else {
        this.logger.log('⏳ Pending Migrations: None');
      }

      this.logger.log('');
      this.logger.log(`Summary: ${executed.length} executed, ${pending.length} pending`);
    } catch (error: any) {
      this.logger.error('❌ Failed to get migration status:', error.message);
      throw error;
    }
  }
}
