import { Command, CommandRunner, Option } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Migrate Fresh Command
 *
 * Drops all tables and re-runs all migrations from scratch.
 * Similar to Laravel's `php artisan migrate:fresh`.
 *
 * WARNING: This command will destroy all data in the database!
 *
 * @description CLI command for fresh migrations
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Drop all tables and re-run migrations
 * npm run console migrate:fresh
 *
 * # Fresh migrations with seeding
 * npm run console migrate:fresh --seed
 * ```
 */
@Injectable()
@Command({
  name: 'migrate:fresh',
  description: 'Drop all tables and re-run all migrations',
})
export class MigrateFreshCommand extends CommandRunner {
  private readonly logger = new Logger(MigrateFreshCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  async run(inputs: string[], options?: MigrateFreshOptions): Promise<void> {
    try {
      const migrator = this.orm.getMigrator();
      const schemaGenerator = this.orm.getSchemaGenerator();

      this.logger.warn('⚠️  WARNING: This will drop all tables and destroy all data!');

      // Drop all tables
      this.logger.log('Dropping all tables...');
      await schemaGenerator.dropSchema({
        dropMigrationsTable: true,
        dropDb: false,
      });
      this.logger.log('✅ All tables dropped');

      // Run all migrations
      this.logger.log('\nRunning all migrations...');
      const result = await migrator.up();

      this.logger.log(`\n✅ Successfully ran ${result.length} migration(s)`);
      result.forEach((migration) => {
        this.logger.log(`  ✓ ${migration.name}`);
      });

      // Run seeders if requested
      if (options?.seed) {
        this.logger.log('\nRunning seeders...');
        this.logger.log('⚠️  Seeder execution should be implemented in db:seed command');
        // Note: Seeder execution will be handled by the db:seed command
      }
    } catch (error: any) {
      this.logger.error('❌ Fresh migration failed:', error.message);
      throw error;
    }
  }

  // @ts-ignore - nest-commander decorator signature mismatch
  @Option({
    flags: '--seed',
    description: 'Run seeders after migrations',
  })
  parseSeed(): boolean {
    return true;
  }
}

interface MigrateFreshOptions {
  seed?: boolean;
}
