import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';
import { randomUUID } from 'crypto';

/**
 * Correlation ID Middleware
 *
 * Manages correlation IDs for distributed request tracing across multiple
 * microservices. Unlike Request ID (unique per request), Correlation ID
 * persists across service boundaries for end-to-end tracing.
 *
 * @description
 * Correlation IDs enable:
 * - End-to-end request tracing across microservices
 * - Correlating logs from multiple services for a single user action
 * - Debugging distributed system issues
 * - Performance monitoring across service boundaries
 * - Identifying bottlenecks in microservice chains
 *
 * @features
 * - Preserves correlation ID from upstream services
 * - Generates new correlation ID if none provided
 * - Propagates correlation ID in response headers
 * - Compatible with APM tools (DataDog, New Relic, etc.)
 * - Stores in request object for downstream propagation
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(CorrelationIdMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 *
 * @example Microservice flow
 * ```
 * Client Request
 *   ↓ (generates correlation-id: abc-123)
 * Service A (API Gateway)
 *   ↓ (forwards correlation-id: abc-123)
 * Service B (Auth Service)
 *   ↓ (forwards correlation-id: abc-123)
 * Service C (Database Service)
 *   All services log with same correlation-id: abc-123
 * ```
 *
 * @example Using correlation ID in HTTP clients
 * ```typescript
 * // When calling another microservice
 * const correlationId = req.headers['x-correlation-id'];
 * await axios.get('https://other-service/api', {
 *   headers: { 'X-Correlation-ID': correlationId }
 * });
 * ```
 *
 * @see https://www.enterpriseintegrationpatterns.com/patterns/messaging/CorrelationIdentifier.html
 */
@Injectable()
export class CorrelationIdMiddleware implements NestMiddleware {
  /**
   * Header name for correlation ID
   * Standard header name used across microservices
   *
   * @private
   */
  private readonly headerName = 'X-Correlation-ID';

  /**
   * Manage correlation ID for distributed tracing
   *
   * @param req - Express request object
   * @param res - Express response object
   * @param next - Next function to call
   */
  use(req: Request, res: Response, next: NextFunction): void {
    // Check if correlation ID was provided by upstream service or client
    // This is the key to distributed tracing - preserve the ID across services
    let correlationId = req.headers[this.headerName.toLowerCase()] as string;

    // If no correlation ID provided, this is the entry point - generate new one
    // This happens when the request originates from a client (not from another service)
    if (!correlationId) {
      correlationId = this.generateCorrelationId();
    }

    // Store correlation ID in request headers for easy access
    // Controllers and services can read this to include in logs
    req.headers[this.headerName.toLowerCase()] = correlationId;

    // Add correlation ID to response headers
    // This allows:
    // 1. Clients to see which correlation ID was used
    // 2. Downstream services to extract and propagate it
    // 3. Debugging and support to reference the correlation ID
    res.setHeader(this.headerName, correlationId);

    next();
  }

  /**
   * Generate a new correlation ID
   * Used when this service is the entry point (no upstream correlation ID)
   *
   * @returns New correlation ID
   * @private
   */
  private generateCorrelationId(): string {
    // Generate UUID v4 for correlation ID
    // Format: corr-xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
    // Prefix helps identify correlation IDs in logs
    return `corr-${randomUUID()}`;
  }
}
