import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';

/**
 * Response Time Middleware
 *
 * Tracks and adds X-Response-Time header to all responses showing
 * how long the request took to process in milliseconds.
 *
 * @description
 * This middleware:
 * - Measures request processing time
 * - Adds X-Response-Time header to response
 * - Useful for performance monitoring
 * - Helps identify slow endpoints
 * - Integrates with monitoring tools
 *
 * @features
 * - High-precision timing
 * - Minimal overhead
 * - Automatic header addition
 * - Compatible with APM tools
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(ResponseTimeMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 *
 * @example Response header
 * ```
 * HTTP/1.1 200 OK
 * X-Response-Time: 45.23ms
 * Content-Type: application/json
 * ```
 */
@Injectable()
export class ResponseTimeMiddleware implements NestMiddleware {
  /**
   * Track response time and add header
   *
   * @param req - Express request object
   * @param res - Express response object
   * @param next - Next function to call
   */
  use(req: Request, res: Response, next: NextFunction): void {
    // Record start time using high-resolution time
    const startTime = process.hrtime();

    // Hook into response finish event
    res.on('finish', () => {
      // Calculate elapsed time in milliseconds
      const [seconds, nanoseconds] = process.hrtime(startTime);
      const milliseconds = seconds * 1000 + nanoseconds / 1000000;

      // Add X-Response-Time header
      res.setHeader('X-Response-Time', `${milliseconds.toFixed(2)}ms`);
    });

    next();
  }
}
