import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';
import { randomUUID } from 'crypto';

/**
 * Trace ID Middleware
 *
 * Manages distributed tracing IDs for Application Performance Monitoring (APM)
 * tools like Datadog, New Relic, Dynatrace, etc. Trace IDs track requests
 * across distributed systems and help identify performance bottlenecks.
 *
 * @description
 * Trace IDs enable:
 * - Integration with APM tools for performance monitoring
 * - Span tracking across microservices
 * - Performance bottleneck identification
 * - Service dependency mapping
 * - Request flow visualization
 *
 * @features
 * - Preserves trace ID from APM tools or upstream services
 * - Generates trace ID if none provided
 * - Compatible with OpenTelemetry, Jaeger, Zipkin
 * - Supports W3C Trace Context standard
 * - Propagates trace ID to downstream services
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(TraceIdMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 *
 * @example APM integration
 * ```typescript
 * // Datadog example
 * import { tracer } from 'dd-trace';
 * const span = tracer.scope().active();
 * const traceId = span?.context().toTraceId();
 * ```
 *
 * @see https://www.w3.org/TR/trace-context/
 * @see https://opentelemetry.io/docs/concepts/signals/traces/
 */
@Injectable()
export class TraceIdMiddleware implements NestMiddleware {
  /**
   * Header name for trace ID
   * Compatible with W3C Trace Context standard
   *
   * @private
   */
  private readonly headerName = 'X-Trace-ID';

  /**
   * Manage trace ID for APM and distributed tracing
   *
   * @param req - Express request object
   * @param res - Express response object
   * @param next - Next function to call
   */
  use(req: Request, res: Response, next: NextFunction): void {
    // Check for trace ID from APM tool or upstream service
    // Common header names used by APM tools:
    // - X-Trace-ID (custom)
    // - traceparent (W3C standard)
    // - X-B3-TraceId (Zipkin)
    // - X-Amzn-Trace-Id (AWS X-Ray)
    let traceId =
      (req.headers[this.headerName.toLowerCase()] as string) ||
      (req.headers['traceparent'] as string) ||
      (req.headers['x-b3-traceid'] as string);

    // If no trace ID provided, generate a new one
    if (!traceId) {
      traceId = this.generateTraceId();
    }

    // Store trace ID in request headers
    req.headers[this.headerName.toLowerCase()] = traceId;

    // Add trace ID to response headers
    // This allows clients and APM tools to correlate requests
    res.setHeader(this.headerName, traceId);

    next();
  }

  /**
   * Generate a new trace ID
   * Format compatible with APM tools
   *
   * @returns New trace ID
   * @private
   */
  private generateTraceId(): string {
    // Generate trace ID in format: trace-{uuid}
    // APM tools typically use 128-bit or 64-bit trace IDs
    return `trace-${randomUUID()}`;
  }
}
