import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';

/**
 * User Agent Parser Middleware
 *
 * Parses the User-Agent header to extract detailed information about
 * the client's browser, operating system, and device type.
 *
 * @description
 * Extracted information includes:
 * - Browser name and version
 * - Operating system
 * - Device type (desktop, mobile, tablet)
 * - Engine name and version
 * - Bot detection
 *
 * @features
 * - Browser detection (Chrome, Firefox, Safari, Edge, etc.)
 * - OS detection (Windows, macOS, Linux, iOS, Android)
 * - Device type identification
 * - Bot/crawler detection
 * - Stores parsed data in request object
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(UserAgentParserMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 *
 * @example Accessing parsed data in controllers
 * ```typescript
 * @Get()
 * async findAll(@Req() req: Request) {
 *   const userAgent = req['userAgent'];
 *   console.log(userAgent);
 *   // { browser: 'Chrome', version: '120.0', os: 'Windows', device: 'desktop' }
 * }
 * ```
 */
@Injectable()
export class UserAgentParserMiddleware implements NestMiddleware {
  /**
   * Parse user agent and enrich request
   *
   * @param req - Express request object
   * @param res - Express response object
   * @param next - Next function to call
   */
  use(req: Request, res: Response, next: NextFunction): void {
    // Get user agent string from headers
    const userAgentString = req.headers['user-agent'] || '';

    // Parse user agent
    const parsed = this.parseUserAgent(userAgentString);

    // Store parsed data in request object for later access
    (req as any)['userAgent'] = parsed;

    // Add custom header with device type (optional)
    if (parsed.device) {
      res.setHeader('X-Device-Type', parsed.device);
    }

    next();
  }

  /**
   * Parse user agent string
   *
   * @param ua - User agent string
   * @returns Parsed user agent information
   * @private
   */
  private parseUserAgent(ua: string): {
    browser: string;
    version: string;
    os: string;
    device: string;
    isBot: boolean;
    raw: string;
  } {
    const result = {
      browser: 'Unknown',
      version: '',
      os: 'Unknown',
      device: 'desktop',
      isBot: false,
      raw: ua,
    };

    // Check if bot/crawler
    result.isBot = this.isBot(ua);

    // Detect browser
    if (ua.includes('Chrome') && !ua.includes('Edg')) {
      result.browser = 'Chrome';
      result.version = this.extractVersion(ua, /Chrome\/([0-9.]+)/);
    } else if (ua.includes('Edg')) {
      result.browser = 'Edge';
      result.version = this.extractVersion(ua, /Edg\/([0-9.]+)/);
    } else if (ua.includes('Firefox')) {
      result.browser = 'Firefox';
      result.version = this.extractVersion(ua, /Firefox\/([0-9.]+)/);
    } else if (ua.includes('Safari') && !ua.includes('Chrome')) {
      result.browser = 'Safari';
      result.version = this.extractVersion(ua, /Version\/([0-9.]+)/);
    } else if (ua.includes('Opera') || ua.includes('OPR')) {
      result.browser = 'Opera';
      result.version = this.extractVersion(ua, /(?:Opera|OPR)\/([0-9.]+)/);
    }

    // Detect OS
    if (ua.includes('Windows NT')) {
      result.os = 'Windows';
    } else if (ua.includes('Mac OS X')) {
      result.os = 'macOS';
    } else if (ua.includes('Linux')) {
      result.os = 'Linux';
    } else if (ua.includes('Android')) {
      result.os = 'Android';
    } else if (ua.includes('iOS') || ua.includes('iPhone') || ua.includes('iPad')) {
      result.os = 'iOS';
    }

    // Detect device type
    if (ua.includes('Mobile') || ua.includes('Android')) {
      result.device = 'mobile';
    } else if (ua.includes('Tablet') || ua.includes('iPad')) {
      result.device = 'tablet';
    } else {
      result.device = 'desktop';
    }

    return result;
  }

  /**
   * Check if user agent is a bot/crawler
   *
   * @param ua - User agent string
   * @returns True if bot detected
   * @private
   */
  private isBot(ua: string): boolean {
    const botPatterns = [
      'bot',
      'crawler',
      'spider',
      'scraper',
      'slurp',
      'google',
      'bing',
      'yahoo',
      'duckduck',
    ];

    return botPatterns.some((pattern) => ua.toLowerCase().includes(pattern));
  }

  /**
   * Extract version from user agent using regex
   *
   * @param ua - User agent string
   * @param pattern - Regex pattern to match version
   * @returns Version string or empty
   * @private
   */
  private extractVersion(ua: string, pattern: RegExp): string {
    const match = ua.match(pattern);
    return match ? match[1] || '' : '';
  }
}
