import { Command } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';
import { spinner, success } from '@nesvel/nestjs-console';

/**
 * Make Resource Command
 *
 * Generates all related files for a complete CRUD resource including:
 * - Entity/Model
 * - Repository
 * - Service
 * - Controller
 * - Module
 * - DTOs (Create and Update)
 *
 * This is a convenience command that saves time by creating the entire
 * resource structure with a single command.
 *
 * @description CLI command for generating complete CRUD resources
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate complete User resource
 * npm run console make:resource User
 *
 * # Generate complete Product resource
 * npm run console make:resource Product
 * ```
 */
@Command({
  name: 'make:resource',
  arguments: '<name>',
  description:
    'Create a complete CRUD resource (model, repository, service, controller, module, DTOs)',
})
export class MakeResourceCommand extends BaseOrmMakeCommand {
  async run(inputs: string[], options?: Record<string, any>): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Resource name argument is required.');
    }

    const spin = spinner(`Generating resource: ${name}...`).start();

    try {
      const fileName = this.toFileName(name);
      const modelName = this.toClassName(name);

      // Build args with path option if provided
      const pathArgs = this.customPath ? ['--path', this.customPath] : [];

      // Execute commands silently - pass through path option
      await this.callSilent('make:model', [name, ...pathArgs]);
      await this.callSilent('make:repository', [name, ...pathArgs]);
      await this.callSilent('make:service', [name, ...pathArgs]);
      await this.callSilent('make:controller', [name, ...pathArgs]);
      await this.callSilent('make:module', [name, ...pathArgs]);
      await this.callSilent('make:dto', [`Create${modelName}`, ...pathArgs]);
      await this.callSilent('make:dto', [`Update${modelName}`, ...pathArgs]);

      spin.succeed();
      
      // Determine base path for output messages
      const basePath = this.customPath || 'src';
      
      success(`\n✨ Complete resource generated for ${name}:`);
      success(`   - Entity: ${basePath}/entities/${fileName}.entity.ts`);
      success(`   - Repository: ${basePath}/repositories/${fileName}.repository.ts`);
      success(`   - Service: ${basePath}/services/${fileName}.service.ts`);
      success(`   - Controller: ${basePath}/controllers/${fileName}.controller.ts`);
      success(`   - Module: ${basePath}/modules/${fileName}.module.ts`);
      success(`   - DTOs: ${basePath}/dtos/create-${fileName}.dto.ts, update-${fileName}.dto.ts`);
    } catch (err: Error | any) {
      spin.fail();
      throw err;
    }
  }
}
