import { Command } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Service Command
 *
 * Generates a new service class that extends BaseService.
 * The service layer handles business logic and interacts with the repository.
 *
 * @description CLI command for generating service classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a UserService
 * npm run console make:service User
 *
 * # Generate a ProductService
 * npm run console make:service Product
 * ```
 */
@Command({
  name: 'make:service',
  arguments: '<name>',
  description: 'Create a new service',
})
export class MakeServiceCommand extends BaseOrmMakeCommand {
  async run(inputs: string[]): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Service name argument is required.');
    }

    // Convert name to PascalCase for class name
    const modelName = this.toClassName(name);

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(name);

    // Create repository class name from model name
    const repositoryName = `${modelName}Repository`;

    // Create repository file name
    const repositoryFileName = `${fileName}.repository`;

    // Create camelCase variable name for repository
    const repositoryVar = this.toVariableName(repositoryName);

    // Generate file from EJS template
    await this.generateFromStub(
      name,
      {
        stubName: 'service',
        outputDir: 'src/services',
        suffix: 'service',
      },
      {
        modelName,
        fileName,
        repositoryName,
        repositoryFileName,
        repositoryVar,
      },
    );
  }
}
