import { Command } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Factory Command
 *
 * Generates a new factory class for creating test data.
 * Factories define default states and can be customized for testing scenarios.
 *
 * @description CLI command for generating factory classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a UserFactory
 * npm run console make:factory User
 *
 * # Generate a ProductFactory
 * npm run console make:factory Product
 * ```
 */
@Command({
  name: 'make:factory',
  arguments: '<name>',
  description: 'Create a new factory',
})
export class MakeFactoryCommand extends BaseOrmMakeCommand {
  async run(inputs: string[]): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Factory name argument is required.');
    }

    // Convert name to PascalCase for class name
    const modelName = this.toClassName(name);

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(name);

    // Generate file from EJS template
    await this.generateFromStub(
      name,
      {
        stubName: 'factory',
        outputDir: 'src/factories',
        suffix: 'factory',
      },
      {
        modelName,
        fileName,
      },
    );
  }
}
