import { Command } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Model Command
 *
 * Generates a new ORM entity/model class with MikroORM decorators.
 * The generated entity extends BaseEntity and includes example properties
 * and placeholder comments for relationships and custom methods.
 *
 * @description CLI command for generating entity classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a User entity
 * npm run console make:model User
 *
 * # Generate a Product entity
 * npm run console make:model Product
 * ```
 */
@Command({
  name: 'make:model',
  arguments: '<name>',
  description: 'Create a new model/entity',
})
export class MakeModelCommand extends BaseOrmMakeCommand {
  /**
   * Execute the make:model command
   *
   * @param inputs - Command arguments [name]
   * @returns Promise that resolves when the entity file is created
   */
  async run(inputs: string[]): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Model name argument is required.');
    }

    // Convert name to PascalCase for class name
    const modelName = this.toClassName(name);

    // Generate file from EJS template
    await this.generateFromStub(
      name,
      {
        stubName: 'model',
        outputDir: 'src/entities',
        suffix: 'entity',
      },
      {
        modelName,
      },
    );
  }
}
