import { Command } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Repository Command
 *
 * Generates a new repository class that extends BaseRepository.
 * The repository provides Laravel Eloquent-inspired methods for database operations.
 *
 * @description CLI command for generating repository classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a UserRepository
 * npm run console make:repository User
 *
 * # Generate a ProductRepository
 * npm run console make:repository Product
 * ```
 */
@Command({
  name: 'make:repository',
  arguments: '<name>',
  description: 'Create a new repository',
})
export class MakeRepositoryCommand extends BaseOrmMakeCommand {
  /**
   * Execute the make:repository command
   *
   * @param inputs - Command arguments [name]
   * @returns Promise that resolves when the repository file is created
   */
  async run(inputs: string[]): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Repository name argument is required.');
    }

    // Convert name to PascalCase for class name
    const modelName = this.toClassName(name);

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(name);

    // Generate file from EJS template
    await this.generateFromStub(
      name,
      {
        stubName: 'repository',
        outputDir: 'src/repositories',
        suffix: 'repository',
      },
      {
        modelName,
        fileName,
      },
    );
  }
}
