import { Command } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Middleware Command
 *
 * Generates a new NestJS middleware class for intercepting HTTP requests,
 * database operations, or implementing cross-cutting concerns.
 *
 * Middleware in NestJS can be used for:
 * - Request/response logging and transformation
 * - Authentication and authorization checks
 * - Request timing and performance monitoring
 * - Entity lifecycle interception
 * - Query modification and result transformation
 * - Error handling and recovery
 *
 * The generated middleware will implement the NestMiddleware interface
 * and can be registered in your application modules.
 *
 * @description CLI command for generating middleware classes
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```bash
 * # Generate a LoggingMiddleware for HTTP request logging
 * npm run console make:middleware Logging
 *
 * # Generate an AuthMiddleware for authentication
 * npm run console make:middleware Auth
 *
 * # Generate a QueryTimingMiddleware for database performance
 * npm run console make:middleware QueryTiming
 * ```
 */
@Command({
  name: 'make:middleware',
  arguments: '<name>',
  description: 'Create a new middleware class',
})
export class MakeMiddlewareCommand extends BaseOrmMakeCommand {
  /**
   * Execute the make:middleware command
   *
   * This method generates a new middleware class file with the following structure:
   * - Injectable decorator for DI container
   * - NestMiddleware interface implementation
   * - use() method for middleware logic
   * - Proper typing for request, response, and next
   *
   * The generated file will be placed in src/middlewares directory
   * with the format: {name}.middleware.ts
   *
   * @param inputs - Command arguments where first element is the middleware name
   * @returns Promise that resolves when the file is created
   * @throws Error if middleware name is not provided
   *
   * @example
   * ```typescript
   * // Running: npm run console make:middleware Logging
   * // Creates: src/middlewares/logging.middleware.ts
   * ```
   */
  async run(inputs: string[]): Promise<void> {
    // Extract middleware name from command arguments
    const [name] = inputs;

    // Validate that middleware name was provided
    if (!name) {
      throw new Error('Middleware name argument is required.');
    }

    // Extract base name by removing 'Middleware' suffix if present
    const baseName = name.replace(/Middleware$/i, '');
    
    // Convert to PascalCase for class name
    const className = this.toClassName(baseName);
    
    // Create middleware class name (always ends with Middleware)
    const middlewareName = `${className}Middleware`;

    // Generate the middleware file from template
    // The stub template should contain:
    // - @Injectable() decorator
    // - NestMiddleware interface
    // - use() method implementation
    await this.generateFromStub(
      baseName, // Use baseName without Middleware suffix
      {
        stubName: 'middleware',
        outputDir: 'src/middlewares',
        suffix: 'middleware',
      },
      {
        className: middlewareName,
      },
    );
  }
}
