import { Command } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Migration Command
 *
 * Generates a new database migration file using Knex.js.
 * Migrations are used to manage database schema changes over time.
 *
 * @description CLI command for generating migration classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a CreateUsersTable migration
 * npm run console make:migration CreateUsersTable
 *
 * # Generate an AddEmailToUsers migration
 * npm run console make:migration AddEmailToUsers
 * ```
 */
@Command({
  name: 'make:migration',
  arguments: '<name>',
  description: 'Create a new database migration',
})
export class MakeMigrationCommand extends BaseOrmMakeCommand {
  async run(inputs: string[]): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Migration name argument is required.');
    }

    // Convert name to PascalCase for class name
    const className = this.toClassName(name);

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(name);

    // Generate table name from migration name
    // CreateUsersTable -> users
    // AddEmailToUsers -> users
    let tableName = fileName.replace(/^create-/, '').replace(/-table$/, '');
    tableName = tableName.replace(/^add-.*-to-/, '').replace(/^update-.*-in-/, '');

    // Add timestamp prefix to migration file
    const timestamp = new Date().toISOString().replace(/[-:]/g, '').split('.')[0];

    // Generate file from EJS template
    await this.generateFromStub(
      name,
      {
        stubName: 'migration',
        outputDir: 'src/migrations',
      },
      {
        tableName,
      },
    );
  }
}
