import { Command, Group } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Event Command
 *
 * Generates a new domain event class that extends BaseEvent.
 * Events represent something that happened in the domain that domain experts care about.
 * They are immutable facts used in event-driven architectures.
 *
 * **What are Domain Events?**
 * Domain events are objects that describe something that happened in the domain.
 * They capture the state change and can be used to trigger side effects,
 * update read models, or integrate with external systems.
 *
 * **When to use Domain Events:**
 * - Decoupling business logic from side effects
 * - Implementing event sourcing patterns
 * - Notifying other parts of the system about changes
 * - Building audit trails and event logs
 * - Integrating with message queues or event streams
 *
 * @description CLI command for generating domain event classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a UserCreatedEvent
 * npm run console make:event UserCreated
 *
 * # Generate an OrderPlacedEvent
 * npm run console make:event OrderPlaced
 *
 * # Generate a PaymentProcessedEvent
 * npm run console make:event PaymentProcessed
 * ```
 */
@Command({
  name: 'make:event',
  arguments: '<name>',
  description: 'Create a new domain event class',
})
@Group('Code Generation')
export class MakeEventCommand extends BaseOrmMakeCommand {
  /**
   * Execute the make:event command
   *
   * Generates a new domain event class file with:
   * - Extends BaseEvent with helper methods
   * - Event-specific properties
   * - getEventName() method for event identifier
   * - fromJSON() method for deserialization
   * - getPayload() method for custom payload structure
   * - toString() method for logging
   * - Comprehensive docblocks and examples
   *
   * The generated file follows these conventions:
   * - File name: {name}.event.ts (kebab-case)
   * - Class name: {Name}Event (PascalCase)
   * - Location: src/events/
   * - Extends BaseEvent
   * - Event name: {name} in kebab-case (e.g., 'user.created')
   *
   * @param inputs - Command arguments where first element is the event name
   * @returns Promise that resolves when the file is created
   * @throws Error if event name is not provided
   *
   * @example
   * ```typescript
   * // Running: npm run console make:event UserCreated
   * // Creates: src/events/user-created.event.ts
   * //
   * // Generated class:
   * // export class UserCreatedEvent extends BaseEvent {
   * //   constructor(
   * //     public readonly userId: string,
   * //     metadata: Record<string, any> = {},
   * //     version: number = 1,
   * //   ) {
   * //     super(metadata, version);
   * //   }
   * //
   * //   public getEventName(): string {
   * //     return 'user.created';
   * //   }
   * // }
   * ```
   */
  async run(inputs: string[]): Promise<void> {
    // Extract event name from command arguments
    const [name] = inputs;

    // Validate that event name was provided
    if (!name) {
      throw new Error('Event name argument is required.');
    }

    // Extract base name by removing 'Event' suffix if present
    const baseName = name.replace(/Event$/i, '');

    // Convert name to PascalCase for class name
    const modelName = this.toClassName(baseName);

    // Create event class name (always ends with Event)
    const className = `${modelName}Event`;

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(baseName);

    // Convert to camelCase for variable name
    const variableName = this.toVariableName(baseName);

    // Generate event name (kebab-case with dots)
    // e.g., UserCreated -> user.created
    const eventName = baseName.replace(/([a-z0-9])([A-Z])/g, '$1.$2').toLowerCase();

    // Determine event action based on common patterns
    // e.g., UserCreated -> was created, OrderPlaced -> was placed
    let eventAction = 'occurred';
    if (baseName.match(/Created$/i)) {
      eventAction = 'was created';
    } else if (baseName.match(/Updated$/i)) {
      eventAction = 'was updated';
    } else if (baseName.match(/Deleted$/i)) {
      eventAction = 'was deleted';
    } else if (baseName.match(/Placed$/i)) {
      eventAction = 'was placed';
    } else if (baseName.match(/Processed$/i)) {
      eventAction = 'was processed';
    } else if (baseName.match(/Sent$/i)) {
      eventAction = 'was sent';
    } else if (baseName.match(/Received$/i)) {
      eventAction = 'was received';
    } else if (baseName.match(/Completed$/i)) {
      eventAction = 'was completed';
    } else if (baseName.match(/Failed$/i)) {
      eventAction = 'failed';
    } else if (baseName.match(/Started$/i)) {
      eventAction = 'started';
    }

    // Generate file from EJS template
    // The stub template includes:
    // - BaseEvent extension
    // - Event-specific properties
    // - getEventName() override
    // - fromJSON() static method
    // - getPayload() method
    // - toString() method
    // - Comprehensive documentation
    await this.generateFromStub(
      baseName, // Use baseName without Event suffix
      {
        suffix: 'event',
        stubName: 'event',
        outputDir: 'src/events',
      },
      {
        className,
        modelName,
        fileName,
        variableName,
        eventName,
        eventAction,
      },
    );
  }
}
