import { Command } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Subscriber Command
 *
 * Generates a new entity subscriber class extending BaseSubscriber for listening
 * to and responding to entity lifecycle events in MikroORM. Subscribers provide
 * a clean way to encapsulate event-driven logic with PubSub integration.
 *
 * Entity subscribers can respond to the following lifecycle events:
 * - afterCreate - After entity is persisted for the first time
 * - afterUpdate - After entity is updated
 * - afterDelete - After entity is removed (hard or soft delete)
 * - afterLoad - After entity is loaded from database (optional)
 *
 * Use subscribers for:
 * - Publishing events to external systems via PubSub
 * - Audit logging and tracking changes
 * - Sending notifications on entity changes
 * - Cascading operations and side effects
 * - Data validation and transformation
 * - Cache invalidation
 * - Event dispatching to other systems
 *
 * @description CLI command for generating entity subscriber classes
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```bash
 * # Generate a UserSubscriber for User entity events
 * npm run console make:subscriber User
 *
 * # Generate a PostSubscriber for Post entity events
 * npm run console make:subscriber Post
 *
 * # Generate an OrderSubscriber for Order entity events
 * npm run console make:subscriber Order
 * ```
 *
 * @example
 * ```typescript
 * // Generated subscriber extends BaseSubscriber:
 * import { UserSubscriber } from '@/subscribers/user.subscriber';
 *
 * @Module({
 *   providers: [UserSubscriber],
 * })
 * export class AppModule {}
 * ```
 */
@Command({
  name: 'make:subscriber',
  arguments: '<name>',
  description: 'Create a new entity subscriber class',
})
export class MakeSubscriberCommand extends BaseOrmMakeCommand {
  /**
   * Execute the make:subscriber command
   *
   * This method generates a new subscriber class file with:
   * - Injectable decorator for NestJS DI
   * - Extends BaseSubscriber with PubSub integration
   * - Entity-specific subscription via getSubscribedEntities()
   * - Lifecycle event handler methods (can be overridden)
   * - Proper typing for event arguments
   * - Logger instance for debugging
   *
   * The generated file follows these conventions:
   * - File name: {name}.subscriber.ts (kebab-case)
   * - Class name: {Name}Subscriber (PascalCase)
   * - Location: src/subscribers/
   * - Extends BaseSubscriber<EntityType>
   *
   * Inherited lifecycle methods from BaseSubscriber:
   * - afterCreate(args: EventArgs<Entity>) - Publishes {entity}.created event
   * - afterUpdate(args: EventArgs<Entity>) - Publishes {entity}.updated event
   * - afterDelete(args: EventArgs<Entity>) - Publishes {entity}.deleted event
   * - afterLoad(args: EventArgs<Entity>) - Publishes {entity}.loaded event (if enabled)
   *
   * @param inputs - Command arguments where first element is the entity name
   * @returns Promise that resolves when the file is created
   * @throws Error if entity name is not provided
   *
   * @example
   * ```typescript
   * // Running: npm run console make:subscriber User
   * // Creates: src/subscribers/user.subscriber.ts
   * //
   * // The subscriber will extend BaseSubscriber and automatically
   * // publish events to PubSub for User entity lifecycle events
   * ```
   */
  async run(inputs: string[]): Promise<void> {
    // Extract entity name from command arguments
    const [name] = inputs;

    // Validate that entity name was provided
    if (!name) {
      throw new Error('Subscriber name argument is required.');
    }

    // Extract entity name by removing 'Subscriber' suffix if present
    const entityBaseName = name.replace(/Subscriber$/i, '');

    // Convert entity name to PascalCase
    const entityName = this.toClassName(entityBaseName);

    // Create subscriber class name (always ends with Subscriber)
    const className = `${entityName}Subscriber`;

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(entityBaseName);

    // Generate the subscriber file from template
    // The stub template extends BaseSubscriber and includes:
    // - @Injectable() decorator for DI container
    // - Constructor with PubSub service injection
    // - getSubscribedEntities() method returning entity class
    // - Optional custom event handler overrides
    // - Proper imports from BaseSubscriber
    await this.generateFromStub(
      name,
      {
        stubName: 'subscriber',
        outputDir: 'src/subscribers',
        suffix: 'subscriber',
      },
      {
        className,
        fileName,
        entityName, // Entity class name (without Subscriber suffix)
      },
    );
  }
}
