import { Command, Group } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Enum Command
 *
 * Generates a new TypeScript enum for use in entity definitions, DTOs,
 * and application logic. Enums provide type-safe alternatives to string
 * or numeric constants and work seamlessly with database column types.
 *
 * Generated enums can be used for:
 * - Entity column types (status, role, type, etc.)
 * - DTO validation and transformation
 * - Query filters and conditions
 * - Application business logic
 * - API request/response types
 *
 * The command supports creating both string enums (recommended) and
 * numeric enums depending on your use case.
 *
 * @description CLI command for generating TypeScript enum files
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```bash
 * # Generate a UserRole enum
 * npm run console make:enum UserRole
 *
 * # Generate a PaymentStatus enum
 * npm run console make:enum PaymentStatus
 *
 * # Generate an OrderType enum
 * npm run console make:enum OrderType
 * ```
 *
 * @example
 * ```typescript
 * // Generated enum can be used in entities:
 * import { UserRole } from '@/enums/user-role.enum';
 *
 * @Entity()
 * export class User extends BaseEntity {
 *   @Property({ type: 'enum' })
 *   @Enum(() => UserRole)
 *   role: UserRole = UserRole.USER;
 * }
 * ```
 */
@Command({
  name: 'make:enum',
  arguments: '<name>',
  description: 'Create a new TypeScript enum',
})
@Group('Code Generation')
export class MakeEnumCommand extends BaseOrmMakeCommand {
  /**
   * Execute the make:enum command
   *
   * This method generates a new TypeScript enum file with:
   * - Exported enum definition
   * - Common enum values based on name (can be customized)
   * - JSDoc documentation for the enum
   * - Helper function to get enum values as array
   * - Helper function to validate enum values
   *
   * The generated file follows these conventions:
   * - File name: {name}.enum.ts (kebab-case)
   * - Enum name: {Name}Enum (PascalCase)
   * - Values: UPPER_SNAKE_CASE
   * - Location: src/enums/
   *
   * @param inputs - Command arguments where first element is the enum name
   * @returns Promise that resolves when the file is created
   * @throws Error if enum name is not provided
   *
   * @example
   * ```typescript
   * // Running: npm run console make:enum UserStatus
   * // Creates: src/enums/user-status.enum.ts
   * //
   * // Generated content:
   * // export enum UserStatus {
   * //   ACTIVE = 'active',
   * //   INACTIVE = 'inactive',
   * //   PENDING = 'pending',
   * // }
   * ```
   */
  async run(inputs: string[]): Promise<void> {
    // Extract enum name from command arguments
    const [name] = inputs;

    // Validate that enum name was provided
    if (!name) {
      throw new Error('Enum name argument is required.');
    }

    // Convert name to PascalCase for enum name
    const enumName = this.toClassName(name);

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(name);

    // Generate the enum file from template
    // The stub template should include:
    // - Enum definition with common values
    // - Helper functions for enum manipulation
    // - Type guards for validation
    // - JSDoc comments for documentation
    await this.generateFromStub(
      name,
      {
        suffix: 'enum',
        stubName: 'enum',
        outputDir: 'src/enums',
      },
      {
        enumName,
        fileName,
      },
    );
  }
}
