import { Command } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make DTO Command
 *
 * Generates a new Data Transfer Object (DTO) class with validation decorators.
 * DTOs are used to validate and transform incoming request data.
 *
 * @description CLI command for generating DTO classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a CreateUserDto
 * npm run console make:dto CreateUser
 *
 * # Generate an UpdateProductDto
 * npm run console make:dto UpdateProduct
 * ```
 */
@Command({
  name: 'make:dto',
  arguments: '<name>',
  description: 'Create a new Data Transfer Object (DTO)',
})
export class MakeDtoCommand extends BaseOrmMakeCommand {
  async run(inputs: string[]): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Dto name argument is required.');
    }

    // Convert name to PascalCase for class name
    const className = this.toClassName(name);

    // Extract model name from DTO name (CreateUser -> User, UpdateProduct -> Product)
    const modelName = className.replace(/^(Create|Update|Delete)/, '');

    // Generate file from EJS template
    await this.generateFromStub(
      name,
      {
        stubName: 'dto',
        outputDir: 'src/dtos',
        suffix: 'Dto',
      },
      {
        modelName,
      },
    );
  }
}
