import { Command, Group } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Module Command
 *
 * Generates a new NestJS module that organizes related components.
 * The module includes imports, controllers, and providers configuration.
 *
 * @description CLI command for generating module classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a UserModule
 * npm run console make:module User
 *
 * # Generate a ProductModule
 * npm run console make:module Product
 * ```
 */
@Command({
  name: 'make:module',
  arguments: '<name>',
  description: 'Create a new NestJS module',
})
@Group('Code Generation')
export class MakeModuleCommand extends BaseOrmMakeCommand {
  async run(inputs: string[]): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Module name argument is required.');
    }

    // Convert name to PascalCase for class name
    const modelName = this.toClassName(name);

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(name);

    // Create repository class name from model name
    const repositoryName = `${modelName}Repository`;

    // Create repository file name
    const repositoryFileName = `${fileName}.repository`;

    // Create service class name from model name
    const serviceName = `${modelName}Service`;

    // Create service file name
    const serviceFileName = `${fileName}.service`;

    // Create controller class name from model name
    const controllerName = `${modelName}Controller`;

    // Create controller file name
    const controllerFileName = `${fileName}.controller`;

    // Generate file from EJS template
    await this.generateFromStub(
      name,
      {
        suffix: 'module',
        stubName: 'module',
        outputDir: 'src',
      },
      {
        modelName,
        fileName,
        repositoryName,
        repositoryFileName,
        serviceName,
        serviceFileName,
        controllerName,
        controllerFileName,
      },
    );
  }
}
