import { Command, Group } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';
import { Injectable } from '@nestjs/common';

/**
 * Make Controller Command
 *
 * Generates a new NestJS REST API controller with CRUD endpoints.
 * The controller handles HTTP requests and delegates to the service layer.
 *
 * @description CLI command for generating controller classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a UserController
 * npm run console make:controller User
 *
 * # Generate a ProductController
 * npm run console make:controller Product
 * ```
 */
@Command({
  name: 'make:controller',
  arguments: '<name>',
  description: 'Create a new REST API controller',
})
@Group('Code Generation')
export class MakeControllerCommand extends BaseOrmMakeCommand {
  /**
   * Execute the make:controller command
   *
   * @param inputs - Command arguments [name]
   * @returns Promise that resolves when the controller file is created
   */
  async run(inputs: string[]): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Controller name argument is required.');
    }

    // Convert name to PascalCase for class name
    const modelName = this.toClassName(name);

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(name);

    // Create service class name from model name
    const serviceName = `${modelName}Service`;

    // Create service file name
    const serviceFileName = `${fileName}.service`;

    // Create camelCase variable name for service
    const serviceVar = this.toVariableName(serviceName);

    // Create API route path (pluralized)
    const routePath = fileName + 's'; // users, products, etc.

    // Generate file from EJS template
    await this.generateFromStub(
      name,
      {
        suffix: 'controller',
        stubName: 'controller',
        outputDir: 'src/controllers',
      },
      {
        modelName,
        fileName,
        serviceName,
        serviceFileName,
        serviceVar,
        routePath,
      },
    );
  }
}
