import { Injectable } from '@nestjs/common';
import {
  EntityManager,
  EntityRepository,
  InjectRepository,
  BaseRepository,
} from '@nesvel/nestjs-orm';
import { Product } from '@/entities/product';

/**
 * Productrepository Repository
 *
 * @description Repository for Product entity
 * @extends BaseRepository<Product>
 * @author Generated by @nesvel/nestjs-orm
 */
@Injectable()
export class Productrepository extends BaseRepository<Product> {
  /**
   * Creates an instance of Productrepository
   *
   * @param repository - The Product entity repository
   * @param em - The entity manager
   */
  constructor(
    @InjectRepository(Product) repository: EntityRepository<Product>,
    em: EntityManager
  ) {
    super(em, repository);
  }

  /**
   * Add custom repository methods here
   *
   * @example
   * async findByEmail(email: string): Promise<Product | null> {
   *   return this.first({ email });
   * }
   *
   * @example
   * async findActive(): Promise<Product[]> {
   *   return this.where({ isActive: true });
   * }
   *
   * @example
   * async findWithRelations(id: number): Promise<Product | null> {
   *   return this.getRepository().findOne(id, {
   *     populate: ['relation1', 'relation2'],
   *   });
   * }
   */
}
