import { Injectable } from '@nestjs/common';
import { BaseService } from '@nesvel/nestjs-orm';
import { Product } from '@/entities/product';
import { ProductRepository } from '@/repositories/product.repository';

/**
 * Productservice Service
 *
 * @description Service layer for Product entity business logic
 * @extends BaseService<Product>
 * @author Generated by @nesvel/nestjs-orm
 */
@Injectable()
export class Productservice extends BaseService<Product> {
  /**
   * Creates an instance of Productservice
   *
   * @param productRepository - The Product repository
   */
  constructor(private readonly productRepository: ProductRepository) {
    super(productRepository);
  }

  /**
   * Add custom service methods here
   *
   * @example
   * async findByEmail(email: string): Promise<Product | null> {
   *   return this.productRepository.first({ email });
   * }
   *
   * @example
   * async activate(id: number): Promise<Product> {
   *   return this.productRepository.update(id, { isActive: true });
   * }
   *
   * @example
   * async processBusinessLogic(data: Partial<Product>): Promise<Product> {
   *   // Complex business logic here
   *   const entity = await this.productRepository.create(data);
   *   // Additional processing
   *   return entity;
   * }
   */
}
