import { Command, Group } from '@nesvel/nestjs-console';
import { CommandRunner, Option } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Migrate Refresh Command
 *
 * Rolls back all migrations and then re-runs them.
 * Similar to Laravel's `php artisan migrate:refresh`.
 *
 * @description CLI command for refreshing migrations
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Rollback and re-run all migrations
 * npm run console migrate:refresh
 *
 * # Refresh with seeding
 * npm run console migrate:refresh --seed
 *
 * # Refresh specific number of steps
 * npm run console migrate:refresh --step=3
 * ```
 */
@Injectable()
@Command({
  name: 'migrate:refresh',
  description: 'Rollback all migrations and re-run them',
})
@Group('Database Migrations')
export class MigrateRefreshCommand extends CommandRunner {
  private readonly logger = new Logger(MigrateRefreshCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  async run(inputs: string[], options?: MigrateRefreshOptions): Promise<void> {
    try {
      const migrator = this.orm.getMigrator();

      this.logger.log('Refreshing migrations...');

      // Rollback all migrations or specific steps
      this.logger.log('Rolling back migrations...');
      const rollbackResult = await migrator.down({
        to: 0, // Rollback all
      });

      if (rollbackResult.length > 0) {
        this.logger.log(`✅ Rolled back ${rollbackResult.length} migration(s)`);
        rollbackResult.forEach((migration) => {
          this.logger.log(`  ✓ ${migration.name}`);
        });
      } else {
        this.logger.log('No migrations to rollback');
      }

      // Re-run all migrations
      this.logger.log('\nRunning migrations...');
      const migrateResult = await migrator.up();

      this.logger.log(`\n✅ Successfully ran ${migrateResult.length} migration(s)`);
      migrateResult.forEach((migration) => {
        this.logger.log(`  ✓ ${migration.name}`);
      });

      // Run seeders if requested
      if (options?.seed) {
        this.logger.log('\nRunning seeders...');
        this.logger.log('⚠️  Seeder execution should be implemented in db:seed command');
        // Note: Seeder execution will be handled by the db:seed command
      }
    } catch (error: any) {
      this.logger.error('❌ Refresh failed:', error.message);
      throw error;
    }
  }

  // @ts-ignore - nest-commander decorator signature mismatch
  @Option({
    flags: '--seed',
    description: 'Run seeders after migrations',
  })
  parseSeed(): boolean {
    return true;
  }

  // @ts-ignore - nest-commander decorator signature mismatch
  @Option({
    flags: '-s, --step [number]',
    description: 'Number of migrations to rollback',
    defaultValue: 0,
  })
  parseStep(val: string): number {
    return parseInt(val, 10);
  }
}

interface MigrateRefreshOptions {
  seed?: boolean;
  step?: number;
}
