import { Command, Group } from '@nesvel/nestjs-console';
import { CommandRunner } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Migrate Reset Command
 *
 * Rolls back all database migrations.
 * Similar to Laravel's `php artisan migrate:reset`.
 *
 * @description CLI command for resetting all migrations
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Rollback all migrations
 * npm run console migrate:reset
 * ```
 */
@Injectable()
@Command({
  name: 'migrate:reset',
  description: 'Rollback all database migrations',
})
@Group('Database Migrations')
export class MigrateResetCommand extends CommandRunner {
  private readonly logger = new Logger(MigrateResetCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  async run(): Promise<void> {
    try {
      const migrator = this.orm.getMigrator();

      this.logger.log('Resetting all migrations...');

      // Get executed migrations
      const executed = await migrator.getExecutedMigrations();

      if (executed.length === 0) {
        this.logger.log('✅ No migrations to reset');
        return;
      }

      this.logger.log(`Found ${executed.length} executed migration(s)`);

      // Rollback all migrations
      const result = await migrator.down({ to: 0 });

      this.logger.log(`\n✅ Successfully rolled back ${result.length} migration(s)`);
      result.forEach((migration) => {
        this.logger.log(`  ✓ ${migration.name}`);
      });
    } catch (error: any) {
      this.logger.error('❌ Reset failed:', error.message);
      throw error;
    }
  }
}
