import { IsNotEmpty } from 'class-validator';
import { IsString } from '@nesvel/nestjs-swagger';

/**
 * CreateOrderdto DTO
 *
 * @description Data Transfer Object for Order validation
 * @author Generated by @nesvel/nestjs-orm
 */
export class CreateOrderDto {
  /**
   * Name field
   */
  @IsString({ description: 'Name of the Order', example: 'Example Name' })
  @IsNotEmpty()
  name!: string;

  /**
   * Add additional validation properties here
   *
   * @example
   * @ApiPropertyOptional({ description: 'Description', example: 'A description' })
   * @IsString()
   * @IsOptional()
   * description?: string;
   *
   * @example
   * @ApiPropertyOptional({ description: 'Active status', example: true })
   * @IsBoolean()
   * @IsOptional()
   * isActive?: boolean;
   *
   * @example
   * @ApiPropertyOptional({ description: 'Age', example: 25 })
   * @IsNumber()
   * @IsOptional()
   * age?: number;
   */
}
