import { Module } from '@nestjs/common';
import { MakeTsconfigCommand, BaseCommand } from '@nesvel/nestjs-console';

import {
  // Make commands
  MakeModelCommand,
  MakeRepositoryCommand,
  MakeServiceCommand,
  MakeSubscriberCommand,
  MakeFactoryCommand,
  MakeSeederCommand,
  MakeMigrationCommand,
  MakeControllerCommand,
  MakeModuleCommand,
  MakeDtoCommand,
  MakeResourceCommand,
  MakeMiddlewareCommand,
  MakeEnumCommand,
  MakeActionCommand,
  MakeEventCommand,

  // Migration commands
  MigrateCommand,
  MigrateRollbackCommand,
  MigrateFreshCommand,
  MigrateRefreshCommand,
  MigrateResetCommand,
  MigrateStatusCommand,

  // Schema commands
  SchemaCreateCommand,
  SchemaDropCommand,
  SchemaUpdateCommand,
  SchemaValidateCommand,

  // Seeder commands
  DbSeedCommand,
  DbSeedListCommand,
  DbSeedRollbackCommand,
  DbSeedRefreshCommand,

  // Entity commands
  EntityListCommand,
  EntityShowCommand,
  EntityGraphCommand,

  // Database commands
  DbShowCommand,
  DbTableCommand,

  // Connection commands
  ConnectionListCommand,
  ConnectionTestCommand,

  // Query commands
  QueryExplainCommand,

  // ORM commands
  OrmInfoCommand,
  OrmDebugCommand,
  OrmMappingDescribeCommand,
  OrmSchemaToolCreateCommand,
  OrmSchemaToolDropCommand,
  OrmSchemaToolUpdateCommand,
  OrmValidateSchemaCommand,
} from './commands';

import { HelpCommand } from './commands/help.command';

/**
 * Console Module
 *
 * Registers all Laravel-style commands for ORM code generation and database management.
 * Includes commands for entities, repositories, services, controllers,
 * modules, DTOs, migrations, factories, seeders, and complete resources.
 *
 * Also includes migration execution commands (migrate, migrate:rollback, etc.)
 * and seeder execution commands (db:seed, db:seed:list, etc.).
 *
 * @description Console module for CLI commands
 * @author Generated by @nesvel/nestjs-orm
 */
@Module({
  providers: [
    // Configuration generators
    MakeTsconfigCommand,

    // Core ORM generators
    MakeModelCommand,
    MakeRepositoryCommand,
    MakeServiceCommand,
    MakeSubscriberCommand,

    // Testing and seeding generators
    MakeFactoryCommand,
    MakeSeederCommand,

    // Database migration generators
    MakeMigrationCommand,

    // NestJS component generators
    MakeControllerCommand,
    MakeModuleCommand,
    MakeDtoCommand,

    // Additional generators
    MakeMiddlewareCommand,
    MakeEnumCommand,
    MakeActionCommand,
    MakeEventCommand,

    // Convenience generators
    MakeResourceCommand,

    // Migration execution commands
    MigrateCommand,
    MigrateRollbackCommand,
    MigrateFreshCommand,
    MigrateRefreshCommand,
    MigrateResetCommand,
    MigrateStatusCommand,

    // Schema management commands
    SchemaCreateCommand,
    SchemaDropCommand,
    SchemaUpdateCommand,
    SchemaValidateCommand,

    // Seeder execution commands
    DbSeedCommand,
    DbSeedListCommand,
    DbSeedRollbackCommand,
    DbSeedRefreshCommand,

    // Entity commands
    EntityListCommand,
    EntityShowCommand,
    EntityGraphCommand,

    // Database commands
    DbShowCommand,
    DbTableCommand,

    // Connection commands
    ConnectionListCommand,
    ConnectionTestCommand,

    // Query commands
    QueryExplainCommand,

    // ORM commands
    OrmInfoCommand,
    OrmDebugCommand,
    OrmMappingDescribeCommand,
    OrmSchemaToolCreateCommand,
    OrmSchemaToolDropCommand,
    OrmSchemaToolUpdateCommand,
    OrmValidateSchemaCommand,

    // Help command
    HelpCommand,
  ],
})
export class ConsoleModule {}
