import { BaseMigration, IRollbackable, Blueprint } from '@nesvel/nestjs-orm';

/**
 * CreateOrderTable Migration
 *
 * Comprehensive demonstration of all Laravel table column types
 * and features available in Nesvel ORM migrations.
 *
 * @description Generated migration with all column types
 * @author Generated by @nesvel/nestjs-orm
 */
export class CreateOrderTable extends BaseMigration implements IRollbackable {
  /**
   * Run the migration (apply changes)
   *
   * Creates the orders table with examples of all available column types
   * and modifiers from the Laravel-style table API.
   */
  up(): Promise<void> | void {
    this.create('orders', (table: Blueprint) => {
      // ============================================================================
      // PRIMARY KEYS
      // ============================================================================
      table.id(); // Auto-incrementing BIGINT primary key

      // ============================================================================
      // STRING TYPES
      // ============================================================================
      table.string('order_number', 50).unique().notNullable();
      table.string('customer_email').notNullable();
      table.text('notes').nullable();
      table.longText('long_description').nullable();
      table.char('status_code', 3).defaultTo('PEN');

      // ============================================================================
      // NUMERIC TYPES
      // ============================================================================
      table.integer('quantity').defaultTo(1);
      table.bigInteger('tracking_number').nullable();
      table.decimal('subtotal', 10, 2).defaultTo(0);
      table.decimal('tax', 10, 2).defaultTo(0);
      table.decimal('total', 10, 2).notNullable();
      table.float('discount_percentage', 5, 2).nullable();
      table.unsignedInteger('priority').defaultTo(0);

      // ============================================================================
      // BOOLEAN
      // ============================================================================
      table.boolean('is_paid').defaultTo(false);
      table.boolean('is_shipped').defaultTo(false);
      table.boolean('is_gift').defaultTo(false);

      // ============================================================================
      // DATE & TIME
      // ============================================================================
      table.date('order_date').notNullable();
      table.datetime('shipped_at').nullable();
      table.timestamp('paid_at').nullable();
      table.timestamp('cancelled_at').nullable();

      // ============================================================================
      // BINARY
      // ============================================================================
      table.binary('signature_data').nullable();

      // ============================================================================
      // JSON
      // ============================================================================
      table.json('shipping_address').nullable();
      table.json('billing_address').nullable();
      table.json('metadata').nullable();

      // ============================================================================
      // UUID
      // ============================================================================
      table.uuid('external_id').unique();

      // ============================================================================
      // ENUM
      // ============================================================================
      table
        .enum('status', ['pending', 'processing', 'shipped', 'delivered', 'cancelled'])
        .defaultTo('pending');
      table.enum('payment_method', ['credit_card', 'paypal', 'bank_transfer', 'cash']).nullable();

      // ============================================================================
      // FOREIGN KEYS
      // ============================================================================
      table.foreignId('user_id').nullable();
      // .references('id')
      // .inTable('users')
      // .onDelete('CASCADE');

      table.foreignId('shipping_method_id').nullable();

      // ============================================================================
      // NETWORK (PostgreSQL)
      // ============================================================================
      table.ipAddress('customer_ip').nullable();

      // ============================================================================
      // POLYMORPHIC RELATIONS
      // ============================================================================
      table.nullableMorphs('trackable'); // trackable_type, trackable_id

      // ============================================================================
      // SPECIAL COLUMNS
      // ============================================================================
      table.rememberToken(); // For stateless sessions

      // ============================================================================
      // TIMESTAMPS & SOFT DELETES
      // ============================================================================
      table.timestamps(); // created_at, updated_at
      table.softDeletes(); // deleted_at
    });

    this.logger.log('✓ Created orders table with all column types');
  }

  /**
   * Reverse the migration
   *
   * Drops the orders table if it exists.
   */
  down(): Promise<void> | void {
    this.drop('orders');
    this.logger.log('✓ Dropped orders table');
  }
}
