import { BaseMigration, IRollbackable } from '@nesvel/nestjs-orm';

/**
 * CreateOrderTable Migration
 *
 * @description Generated migration
 * @author Generated by @nesvel/nestjs-orm
 */
export class CreateOrderTable extends BaseMigration implements IRollbackable {
  /**
   * Run the migration (apply changes)
   *
   * @param context - Migration context with database connection and utilities
   */
  async up(): Promise<void> {
    await this.getSchema().createTable('order', (table) => {
      table.increments('id').primary();
      table.string('name').notNullable();
      table.timestamps(true, true);
    });

    this.context.logger.log('Created table: order');
  }

  /**
   * Reverse the migration (rollback changes)
   */
  async down(): Promise<void> {
    await this.getSchema().dropTableIfExists('order');

    this.context.logger.log('Dropped table: order');
  }
}
