import { BaseMigration, IRollbackable } from '@nesvel/nestjs-orm';

/**
 * CreateOrderTable Migration
 *
 * Comprehensive demonstration of all Laravel Blueprint column types
 * and features available in Nesvel ORM migrations.
 *
 * @description Generated migration with all column types
 * @author Generated by @nesvel/nestjs-orm
 */
export class CreateOrderTable extends BaseMigration implements IRollbackable {
  /**
   * Run the migration (apply changes)
   *
   * Creates the orders table with examples of all available column types
   * and modifiers from the Laravel-style Blueprint API.
   */
  up(): Promise<void> | void {
    this.create('orders', (blueprint) => {
      // ============================================================================
      // PRIMARY KEYS
      // ============================================================================
      blueprint.id(); // Auto-incrementing BIGINT primary key

      // ============================================================================
      // STRING TYPES
      // ============================================================================
      blueprint.string('order_number', 50).unique().notNullable();
      blueprint.string('customer_email').notNullable();
      blueprint.text('notes').nullable();
      blueprint.longText('long_description').nullable();
      blueprint.char('status_code', 3).defaultTo('PEN');

      // ============================================================================
      // NUMERIC TYPES
      // ============================================================================
      blueprint.integer('quantity').defaultTo(1);
      blueprint.bigInteger('tracking_number').nullable();
      blueprint.decimal('subtotal', 10, 2).defaultTo(0);
      blueprint.decimal('tax', 10, 2).defaultTo(0);
      blueprint.decimal('total', 10, 2).notNullable();
      blueprint.float('discount_percentage', 5, 2).nullable();
      blueprint.unsignedInteger('priority').defaultTo(0);

      // ============================================================================
      // BOOLEAN
      // ============================================================================
      blueprint.boolean('is_paid').defaultTo(false);
      blueprint.boolean('is_shipped').defaultTo(false);
      blueprint.boolean('is_gift').defaultTo(false);

      // ============================================================================
      // DATE & TIME
      // ============================================================================
      blueprint.date('order_date').notNullable();
      blueprint.datetime('shipped_at').nullable();
      blueprint.timestamp('paid_at').nullable();
      blueprint.timestamp('cancelled_at').nullable();

      // ============================================================================
      // BINARY
      // ============================================================================
      blueprint.binary('signature_data').nullable();

      // ============================================================================
      // JSON
      // ============================================================================
      blueprint.json('shipping_address').nullable();
      blueprint.json('billing_address').nullable();
      blueprint.json('metadata').nullable();

      // ============================================================================
      // UUID
      // ============================================================================
      blueprint.uuid('external_id').unique();

      // ============================================================================
      // ENUM
      // ============================================================================
      blueprint
        .enum('status', ['pending', 'processing', 'shipped', 'delivered', 'cancelled'])
        .defaultTo('pending');
      blueprint
        .enum('payment_method', ['credit_card', 'paypal', 'bank_transfer', 'cash'])
        .nullable();

      // ============================================================================
      // FOREIGN KEYS
      // ============================================================================
      blueprint.foreignId('user_id').nullable();
      // .references('id')
      // .inTable('users')
      // .onDelete('CASCADE');

      blueprint.foreignId('shipping_method_id').nullable();

      // ============================================================================
      // NETWORK (PostgreSQL)
      // ============================================================================
      blueprint.ipAddress('customer_ip').nullable();

      // ============================================================================
      // POLYMORPHIC RELATIONS
      // ============================================================================
      blueprint.nullableMorphs('trackable'); // trackable_type, trackable_id

      // ============================================================================
      // SPECIAL COLUMNS
      // ============================================================================
      blueprint.rememberToken(); // For stateless sessions

      // ============================================================================
      // TIMESTAMPS & SOFT DELETES
      // ============================================================================
      blueprint.timestamps(); // created_at, updated_at
      blueprint.softDeletes(); // deleted_at
    });

    this.logger.log('✓ Created orders table with all column types');
  }

  /**
   * Reverse the migration
   *
   * Drops the orders table if it exists.
   */
  down(): Promise<void> | void {
    this.drop('orders');
    this.logger.log('✓ Dropped orders table');
  }
}
