import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';
import { AsyncLocalStorage } from 'async_hooks';

/**
 * User Context Middleware
 *
 * Sets user information in async context for access throughout the request
 * lifecycle without explicit parameter passing. Uses Node.js AsyncLocalStorage.
 *
 * @description
 * This middleware:
 * - Creates async context for each request
 * - Stores user information in async local storage
 * - Enables access to user context from any part of code
 * - Useful for logging, auditing, and multi-tenancy
 *
 * @features
 * - Async context management
 * - User context propagation
 * - No explicit parameter passing needed
 * - Works across async operations
 * - Thread-safe context isolation
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(UserContextMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 *
 * @example Accessing user context anywhere
 * ```typescript
 * import { UserContextMiddleware } from '@/middlewares';
 *
 * // In any service or function
 * const context = UserContextMiddleware.getUserContext();
 * console.log(context.userId, context.email);
 * ```
 */
@Injectable()
export class UserContextMiddleware implements NestMiddleware {
  /**
   * Async local storage for user context
   * Provides request-scoped storage that persists across async operations
   *
   * @private
   * @static
   */
  private static asyncLocalStorage = new AsyncLocalStorage<{
    userId?: string;
    email?: string;
    roles?: string[];
    tenantId?: string;
    requestId?: string;
    correlationId?: string;
    [key: string]: any;
  }>();

  /**
   * Set user context in async local storage
   *
   * @param req - Express request object
   * @param res - Express response object
   * @param next - Next function to call
   */
  use(req: Request, res: Response, next: NextFunction): void {
    // Extract user information from request
    const user = req['user'];
    const tenantId = req['tenantId'];
    const requestId = req.headers['x-request-id'] as string;
    const correlationId = req.headers['x-correlation-id'] as string;

    // Build context object
    const context = {
      userId: user?.id || user?.sub,
      email: user?.email,
      roles: user?.roles || [],
      tenantId,
      requestId,
      correlationId,
      timestamp: new Date().toISOString(),
      ip: this.getClientIp(req),
      userAgent: req.headers['user-agent'],
    };

    // Run the rest of the request in async context
    UserContextMiddleware.asyncLocalStorage.run(context, () => {
      next();
    });
  }

  /**
   * Get current user context from async local storage
   * Can be called from anywhere in the request lifecycle
   *
   * @returns User context or undefined
   * @static
   */
  static getUserContext(): any | undefined {
    return UserContextMiddleware.asyncLocalStorage.getStore();
  }

  /**
   * Get client IP address
   *
   * @param req - Express request object
   * @returns Client IP address
   * @private
   */
  private getClientIp(req: Request): string {
    const forwardedFor = req.headers['x-forwarded-for'];

    if (forwardedFor) {
      const ips = Array.isArray(forwardedFor) ? forwardedFor[0] : forwardedFor;
      if (ips) {
        return ips.split(',')[0]?.trim() || 'unknown';
      }
    }

    return req.ip || req.socket.remoteAddress || 'unknown';
  }
}
