import { Command, Group } from '@nesvel/nestjs-console';
import { CommandRunner } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * ORM Validate Schema Command
 *
 * Validates entity mappings and checks for configuration issues.
 *
 * @description CLI command for validating entity mappings
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 */
@Injectable()
@Command({
  name: 'orm:validate-schema',
  description: 'Validate entity mappings',
})
@Group('ORM Utilities')
export class OrmValidateSchemaCommand extends CommandRunner {
  private readonly logger = new Logger(OrmValidateSchemaCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  async run(): Promise<void> {
    try {
      this.logger.log('Validating entity mappings...\n');

      const schemaGenerator = this.orm.getSchemaGenerator();
      const updateSQL = await schemaGenerator.getUpdateSchemaSQL({ safe: false });

      if (!updateSQL || updateSQL.trim().length === 0) {
        this.logger.log('✅ Entity mappings are valid');
        this.logger.log('✅ Schema matches entity definitions');
        return;
      }

      this.logger.error('❌ Validation failed - schema does not match entities\n');
      this.logger.log('Required changes:');
      this.logger.log('='.repeat(60));
      this.logger.log(updateSQL);
      this.logger.log('='.repeat(60));

      process.exit(1);
    } catch (error: any) {
      this.logger.error('❌ Validation failed:', error.message);
      throw error;
    }
  }
}
