import { Command, Group } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Action Command
 *
 * Generates a new action class that extends BaseAction.
 * Actions encapsulate specific business logic following the Command pattern,
 * making your code more modular, testable, and maintainable.
 *
 * **What are Actions?**
 * Actions are injectable classes that contain a single piece of business logic.
 * They help separate concerns by moving business logic out of controllers and
 * into dedicated, reusable classes.
 *
 * **When to use Actions:**
 * - Complex business logic that shouldn't be in controllers
 * - Logic that needs to be reused across multiple controllers
 * - Operations that require multiple dependencies (repositories, services)
 * - Logic that needs to be tested in isolation
 *
 * @description CLI command for generating action classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a CreateUserAction
 * npm run console make:action CreateUser
 *
 * # Generate an UpdateProductAction
 * npm run console make:action UpdateProduct
 *
 * # Generate a SendWelcomeEmailAction
 * npm run console make:action SendWelcomeEmail
 * ```
 */
@Command({
  name: 'make:action',
  arguments: '<name>',
  description: 'Create a new action class',
})
@Group('Code Generation')
export class MakeActionCommand extends BaseOrmMakeCommand {
  /**
   * Execute the make:action command
   *
   * Generates a new action class file with:
   * - @Injectable() decorator for dependency injection
   * - Extends BaseAction with proper typing
   * - execute() method for business logic
   * - validateInput() method for input validation
   * - transformOutput() method for output transformation
   * - Constructor for dependency injection
   * - Comprehensive docblocks and examples
   *
   * The generated file follows these conventions:
   * - File name: {name}.action.ts (kebab-case)
   * - Class name: {Name}Action (PascalCase)
   * - Location: src/actions/
   * - Extends BaseAction<TInput, TOutput>
   *
   * @param inputs - Command arguments where first element is the action name
   * @returns Promise that resolves when the file is created
   * @throws Error if action name is not provided
   *
   * @example
   * ```typescript
   * // Running: npm run console make:action CreateUser
   * // Creates: src/actions/create-user.action.ts
   * //
   * // Generated class:
   * // @Injectable()
   * // export class CreateUserAction extends BaseAction<CreateUserDto, User> {
   * //   async execute(data: CreateUserDto): Promise<User> {
   * //     // Business logic here
   * //   }
   * // }
   * ```
   */
  async run(inputs: string[]): Promise<void> {
    // Extract action name from command arguments
    const [name] = inputs;

    // Validate that action name was provided
    if (!name) {
      throw new Error('Action name argument is required.');
    }

    // Extract base name by removing 'Action' suffix if present
    const baseName = name.replace(/Action$/i, '');

    // Convert name to PascalCase for class name
    const modelName = this.toClassName(baseName);

    // Create action class name (always ends with Action)
    const className = `${modelName}Action`;

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(baseName);

    // Convert to camelCase for variable name
    const variableName = this.toVariableName(baseName);

    // Generate file from EJS template
    // The stub template includes:
    // - @Injectable() decorator
    // - BaseAction extension
    // - execute() method with TODO comments
    // - validateInput() and transformOutput() methods
    // - Constructor with injection examples
    // - Comprehensive documentation
    await this.generateFromStub(
      baseName, // Use baseName without Action suffix
      {
        suffix: 'action',
        stubName: 'action',
        outputDir: 'src/actions',
      },
      {
        className,
        modelName,
        fileName,
        variableName,
      },
    );
  }
}
