import { Command, Group } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Factory Command
 *
 * Generates a new factory class for creating test data.
 * Factories define default states and can be customized for testing scenarios.
 *
 * @description CLI command for generating factory classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a UserFactory
 * npm run console make:factory User
 *
 * # Generate a ProductFactory
 * npm run console make:factory Product
 * ```
 */
@Command({
  name: 'make:factory',
  arguments: '<name>',
  description: 'Create a new factory',
})
@Group('Code Generation')
export class MakeFactoryCommand extends BaseOrmMakeCommand {
  async run(inputs: string[]): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Factory name argument is required.');
    }

    // Remove 'Factory' suffix if already present to avoid duplication
    const baseName = name.replace(/Factory$/i, '');

    // Convert name to PascalCase for class name (will have Factory suffix added)
    const modelName = this.toClassName(baseName);
    const className = `${modelName}${this.toClassName('factory')}`;

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(baseName);

    // Convert to camelCase for variable name
    const variableName = this.toVariableName(baseName);

    // Generate file from EJS template
    await this.generateFromStub(
      name,
      {
        suffix: 'factory',
        stubName: 'factory',
        outputDir: 'src/factories',
      },
      {
        className,
        modelName,
        fileName,
        variableName,
      },
    );
  }
}
