import { Command, Group } from '@nesvel/nestjs-console';
import { BaseOrmMakeCommand } from '../base-orm-make.command';

/**
 * Make Seeder Command
 *
 * Generates a new seeder class for populating the database with initial data.
 * Seeders are used to insert default or test data into the database.
 *
 * @description CLI command for generating database seeder classes
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Generate a UserSeeder
 * npm run console make:seeder User
 *
 * # Generate a ProductSeeder
 * npm run console make:seeder Product
 * ```
 */
@Command({
  name: 'make:seeder',
  arguments: '<name>',
  description: 'Create a new seeder',
})
@Group('Code Generation')
export class MakeSeederCommand extends BaseOrmMakeCommand {
  async run(inputs: string[]): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Seeder name argument is required.');
    }

    // Remove 'Seeder' suffix if already present to avoid duplication
    const baseName = name.replace(/Seeder$/i, '');

    // Convert name to PascalCase for class name (will have Seeder suffix added)
    const modelName = this.toClassName(baseName);
    const className = `${modelName}Seeder`;

    // Convert name to kebab-case for file name
    const fileName = this.toFileName(baseName);

    // Convert to camelCase for variable name
    const variableName = this.toVariableName(baseName);

    // Generate file from EJS template
    await this.generateFromStub(
      name,
      {
        suffix: 'seeder',
        stubName: 'seeder',
        outputDir: 'src/seeders',
      },
      {
        className,
        modelName,
        fileName,
        variableName,
      },
    );
  }
}
