import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';

/**
 * API Version Middleware
 *
 * Handles API versioning through headers or URL paths. Supports multiple
 * versioning strategies for backward compatibility and gradual API evolution.
 *
 * @description
 * Versioning strategies supported:
 * - Header-based: X-API-Version or Accept-Version header
 * - URL-based: /v1/users, /v2/users
 * - Accept header: application/vnd.api+json;version=1
 *
 * @features
 * - Multiple versioning strategies
 * - Version validation
 * - Default version fallback
 * - Version deprecation warnings
 * - Adds version to response headers
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(ApiVersionMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 */
@Injectable()
export class ApiVersionMiddleware implements NestMiddleware {
  private readonly defaultVersion = process.env.API_DEFAULT_VERSION || '1';
  private readonly supportedVersions = (process.env.API_SUPPORTED_VERSIONS || '1,2').split(',');

  use(req: Request, res: Response, next: NextFunction): void {
    // Extract version from various sources
    const version = this.extractVersion(req);

    // Validate and set version
    const validVersion = this.validateVersion(version);
    (req as Request & { apiVersion: string }).apiVersion = validVersion;

    // Add version to response header
    res.setHeader('X-API-Version', validVersion);

    next();
  }

  private extractVersion(req: Request): string {
    // 1. Check X-API-Version header
    const headerVersion = req.headers['x-api-version'] as string;
    if (headerVersion) return headerVersion;

    // 2. Check URL path (/v1/users)
    const pathMatch = req.path.match(/^\/v(\d+)\//);
    if (pathMatch?.[1]) return pathMatch[1];

    // 3. Use default version
    return this.defaultVersion;
  }

  private validateVersion(version: string): string {
    return this.supportedVersions.includes(version) ? version : this.defaultVersion;
  }
}
