import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';

/**
 * Tenant Context Middleware
 *
 * Extracts tenant ID from various sources (header, subdomain, JWT) and sets
 * tenant context for multi-tenancy support.
 *
 * @description
 * Multi-tenancy approaches supported:
 * - Header-based: X-Tenant-ID header
 * - Subdomain-based: tenant.example.com
 * - JWT-based: Tenant ID in JWT payload
 * - Path-based: /tenants/:tenantId/...
 *
 * @features
 * - Multiple tenant identification methods
 * - Tenant context propagation
 * - Subdomain parsing
 * - JWT tenant extraction
 * - Tenant validation hooks
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(TenantContextMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 *
 * @example Accessing tenant in controllers
 * ```typescript
 * @Get()
 * async findAll(@Req() req: Request) {
 *   const tenantId = req['tenantId'];
 *   // Filter data by tenant
 *   return this.service.findByTenant(tenantId);
 * }
 * ```
 */
@Injectable()
export class TenantContextMiddleware implements NestMiddleware {
  /**
   * Extract tenant context and set in request
   *
   * @param req - Express request object
   * @param res - Express response object
   * @param next - Next function to call
   */
  use(req: Request, res: Response, next: NextFunction): void {
    // Extract tenant ID from various sources
    const tenantId = this.extractTenantId(req);

    if (tenantId) {
      // Set tenant context in request
      req['tenantId'] = tenantId;

      // Add tenant ID to response headers (for debugging)
      if (process.env.NODE_ENV === 'development') {
        res.setHeader('X-Tenant-ID', tenantId);
      }
    }

    next();
  }

  /**
   * Extract tenant ID from request
   *
   * @param req - Express request object
   * @returns Tenant ID or null
   * @private
   */
  private extractTenantId(req: Request): string | null {
    // 1. Check X-Tenant-ID header (most explicit)
    const headerTenant = req.headers['x-tenant-id'] as string;
    if (headerTenant) {
      return headerTenant;
    }

    // 2. Extract from subdomain (e.g., tenant1.api.example.com)
    const host = req.headers.host || '';
    const subdomain = this.extractSubdomain(host);
    if (subdomain && this.isValidTenantSubdomain(subdomain)) {
      return subdomain;
    }

    // 3. Extract from JWT token (if user context is set)
    const user = req['user'];
    if (user && user.tenantId) {
      return user.tenantId;
    }

    // 4. Extract from path params (e.g., /api/tenants/:tenantId/...)
    const pathTenant = req.params.tenantId;
    if (pathTenant) {
      return pathTenant;
    }

    return null;
  }

  /**
   * Extract subdomain from host
   *
   * @param host - Host header value
   * @returns Subdomain or null
   * @private
   */
  private extractSubdomain(host: string): string | null {
    // Remove port if present
    const hostname = host.split(':')[0];

    // Split by dots
    const parts = hostname.split('.');

    // Need at least 3 parts for subdomain (subdomain.domain.tld)
    if (parts.length >= 3) {
      return parts[0];
    }

    return null;
  }

  /**
   * Validate if subdomain is a valid tenant identifier
   * (exclude common subdomains like www, api, admin)
   *
   * @param subdomain - Subdomain string
   * @returns True if valid tenant subdomain
   * @private
   */
  private isValidTenantSubdomain(subdomain: string): boolean {
    const excludedSubdomains = ['www', 'api', 'admin', 'app', 'localhost'];
    return !excludedSubdomains.includes(subdomain.toLowerCase());
  }
}
