import { v4 as uuid4 } from 'uuid';

/**
 * BaseEvent
 *
 * Abstract base class for all domain events in the application.
 * Provides common functionality for event handling, including metadata management,
 * serialization, and timestamp tracking.
 *
 * **Purpose:**
 * Domain events represent something that happened in the domain that domain experts
 * care about. They are immutable facts about things that have already happened.
 *
 * **Usage:**
 * Extend this class to create custom domain events. Events can be dispatched
 * through the event emitter or event bus and handled by event listeners.
 *
 * @description Base class for domain events with helper functions
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * export class UserCreatedEvent extends BaseEvent {
 *   constructor(
 *     public readonly userId: string,
 *     public readonly email: string,
 *   ) {
 *     super();
 *   }
 * }
 *
 * // Usage with inherited make() method
 * const event = UserCreatedEvent.make('123', 'user@example.com');
 * eventEmitter.emit('user.created', event);
 *
 * // With metadata chaining
 * const event = UserCreatedEvent.make('123', 'user@example.com')
 *   .withMetadata({ correlationId: 'abc', userId: '456' });
 * ```
 */
export abstract class BaseEvent {
  /**
   * Unique identifier for this event instance
   *
   * @description Automatically generated UUID for tracking individual event occurrences
   */
  public readonly eventId: string;

  /**
   * Timestamp when the event was created
   *
   * @description ISO 8601 formatted timestamp of event creation
   */
  public readonly occurredAt: Date;

  /**
   * Event metadata for additional context
   *
   * @description Optional metadata that can be attached to events for tracking,
   * correlation, or additional context information
   */
  private _metadata: Record<string, any>;

  /**
   * Event version for schema evolution
   *
   * @description Version number to handle event schema changes over time
   */
  public readonly version: number;

  /**
   * Creates an instance of BaseEvent
   *
   * @description Initializes the event with a unique ID and timestamp
   */
  constructor() {
    this.version = 1;
    this._metadata = {};
    this.occurredAt = new Date();
    this.eventId = this.generateEventId();
  }

  /**
   * Static factory method to create event instances
   *
   * Generic factory method that works for all event subclasses.
   * Automatically infers the correct event type and accepts constructor arguments.
   *
   * @param args - Constructor arguments for the event class
   * @returns New instance of the event class
   *
   * @description Creates a new event instance using the subclass constructor
   *
   * @example
   * ```typescript
   * // Simple usage
   * const event = UserCreatedEvent.make('123', 'user@example.com');
   *
   * // With metadata chaining
   * const event = OrderCreatedEvent.make('order-123', 'customer-456', 99.99)
   *   .withMetadata({ correlationId: 'abc-123' })
   *   .addMetadata('source', 'api');
   *
   * // Type-safe - TypeScript knows the exact type
   * event.userId; // ✓ Type-safe access to event properties
   * ```
   */
  static make<T extends BaseEvent>(this: new (...args: any[]) => T, ...args: any[]): T {
    // Create a new instance using the constructor with all provided arguments
    // 'this' refers to the actual event class (e.g., UserCreatedEvent)
    // The spread operator passes all arguments to the constructor
    return new this(...args);
  }

  /**
   * Get the event name
   *
   * Returns the event name based on the class name.
   * Can be overridden to provide custom event names.
   *
   * @returns The event name
   *
   * @description Converts class name to kebab-case event name
   * (e.g., UserCreatedEvent -> user.created)
   *
   * @example
   * ```typescript
   * const event = new UserCreatedEvent('123', 'user@example.com');
   * console.log(event.getEventName()); // 'user.created'
   * ```
   */
  public getEventName(): string {
    const className = this.constructor.name;

    // Remove 'Event' suffix if present
    const baseName = className.replace(/Event$/, '');

    // Convert PascalCase to kebab-case
    return baseName.replace(/([a-z0-9])([A-Z])/g, '$1.$2').toLowerCase();
  }

  /**
   * Serialize the event to JSON
   *
   * Converts the event to a plain JSON object for storage or transmission.
   * Includes all event properties and metadata.
   *
   * @returns Plain object representation of the event
   *
   * @description Serializes the event to a JSON-compatible object
   *
   * @example
   * ```typescript
   * const event = new UserCreatedEvent('123', 'user@example.com');
   * const json = event.toJSON();
   * console.log(JSON.stringify(json));
   * ```
   */
  public toJSON(): Record<string, any> {
    return {
      eventId: this.eventId,
      eventName: this.getEventName(),
      occurredAt: this.occurredAt.toISOString(),
      version: this.version,
      metadata: this.metadata,
      payload: this.getPayload(),
    };
  }

  /**
  /**
   * Get metadata
   *
   * Returns the event metadata object.
   *
   * @returns Event metadata
   *
   * @description Returns the metadata object for the event
   */
  public get metadata(): Record<string, any> {
    return this._metadata;
  }

  /**
   * Get event payload
   *
   * Returns the event-specific data (properties excluding base properties).
   * Automatically extracts all public readonly properties from the event.
   *
   * @returns Event payload data
   *
   * @description Extracts event-specific properties, excluding base class properties
   *
   * @example
   * ```typescript
   * class UserCreatedEvent extends BaseEvent {
   *   constructor(
   *     public readonly userId: string,
   *     public readonly email: string,
   *   ) {
   *     super();
   *   }
   * }
   *
   * const event = new UserCreatedEvent('123', 'user@example.com');
   * console.log(event.getPayload()); // { userId: '123', email: 'user@example.com' }
   * ```
   */
  public getPayload(): Record<string, any> {
    const payload: Record<string, any> = {};
    const baseProperties = ['eventId', 'occurredAt', '_metadata', 'version'];

    // Get all properties from the instance
    for (const key of Object.keys(this)) {
      if (!baseProperties.includes(key)) {
        payload[key] = (this as any)[key];
      }
    }

    return payload;
  }
  /**
   * Set metadata
   *
   * Sets the entire metadata object for the event.
   * Useful for adding correlation IDs, user context, etc.
   *
   * @param metadata - Metadata object to set
   * @returns This event instance for chaining
   *
   * @description Sets the metadata object for the event
   *
   * @example
   * ```typescript
   * const event = UserCreatedEvent.make('123', 'user@example.com')
   *   .withMetadata({ correlationId: 'abc-123', userId: '456' });
   * ```
   */
  public withMetadata(metadata: Record<string, any>): this {
    this._metadata = { ...this._metadata, ...metadata };
    return this;
  }

  /**
   * Add metadata to the event
   *
   * Adds a single metadata key-value pair to the event.
   * Returns the event instance for method chaining.
   *
   * @param key - Metadata key
   * @param value - Metadata value
   * @returns This event instance for chaining
   *
   * @description Adds metadata for tracking or correlation purposes
   *
   * @example
   * ```typescript
   * const event = UserCreatedEvent.make('123', 'user@example.com')
   *   .addMetadata('correlationId', 'abc-123')
   *   .addMetadata('source', 'api');
   * ```
   */
  public addMetadata(key: string, value: any): this {
    this._metadata[key] = value;
    return this;
  }

  /**
   * Get metadata value by key
   *
   * Retrieves a specific metadata value by its key.
   *
   * @param key - Metadata key
   * @param defaultValue - Default value if key doesn't exist
   * @returns Metadata value or default value
   *
   * @description Safe accessor for metadata properties
   *
   * @example
   * ```typescript
   * const correlationId = event.getMetadata('correlationId');
   * const source = event.getMetadata('source', 'unknown');
   * ```
   */
  public getMetadata<T = any>(key: string, defaultValue?: T): T | undefined {
    return this.metadata[key] ?? defaultValue;
  }

  /**
   * Check if event has specific metadata
   *
   * Checks if a metadata key exists on the event.
   *
   * @param key - Metadata key to check
   * @returns True if metadata key exists
   *
   * @description Checks for metadata key existence
   *
   * @example
   * ```typescript
   * if (event.hasMetadata('correlationId')) {
   *   console.log('Event has correlation ID');
   * }
   * ```
   */
  public hasMetadata(key: string): boolean {
    return key in this.metadata;
  }

  /**
   * Generate a unique event ID
   *
   * Generates a UUID v4 for the event instance.
   * Can be overridden to use a different ID generation strategy.
   *
   * @returns Unique event identifier
   *
   * @description Generates a UUID v4 using crypto.randomUUID()
   *
   * @example
   * ```typescript
   * const id = this.generateEventId();
   * console.log(id); // 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
   * ```
   */
  protected generateEventId(): string {
    // Generate UUID v4
    return uuid4();
  }

  /**
   * Create event from JSON
   *
   * Static factory method to reconstruct an event from its JSON representation.
   * Subclasses should override this to properly reconstruct their specific event type.
   *
   * @param json - JSON representation of the event
   * @returns Reconstructed event instance
   *
   * @description Base implementation for event deserialization
   *
   * @example
   * ```typescript
   * class UserCreatedEvent extends BaseEvent {
   *   constructor(
   *     public readonly userId: string,
   *     public readonly email: string,
   *   ) {
   *     super();
   *   }
   *
   *   static fromJSON(json: any): UserCreatedEvent {
   *     const event = new UserCreatedEvent(
   *       json.payload.userId,
   *       json.payload.email,
   *     );
   *     if (json.metadata) {
   *       event.withMetadata(json.metadata);
   *     }
   *     return event;
   *   }
   * }
   *
   * const json = { payload: { userId: '123', email: 'user@example.com' }, metadata: {} };
   * const event = UserCreatedEvent.fromJSON(json);
   * ```
   */
  public static fromJSON(json: Record<string, any>): BaseEvent {
    throw new Error('fromJSON must be implemented by subclass for proper deserialization');
  }

  /**
   * Get a string representation of the event
   *
   * Returns a human-readable string representation of the event.
   * Useful for logging and debugging.
   *
   * @returns String representation
   *
   * @description Provides a formatted string for logging
   *
   * @example
   * ```typescript
   * const event = new UserCreatedEvent('123', 'user@example.com');
   * console.log(event.toString());
   * // '[UserCreatedEvent] (abc-123) occurred at 2024-01-01T00:00:00.000Z'
   * ```
   */
  public toString(): string {
    return `[${this.constructor.name}] (${this.eventId}) occurred at ${this.occurredAt.toISOString()}`;
  }
}
