import { BaseMigration, IRollbackable } from '@nesvel/nestjs-orm';

/**
 * CreateTestUsersTable Migration
 *
 * @description Generated migration
 * @author Generated by @nesvel/nestjs-orm
 */
export class CreateTestUsersTable extends BaseMigration implements IRollbackable {
  /**
   * Run the migration (apply changes)
   *
   * @param context - Migration context with database connection and utilities
   */
  async up(): Promise<void> {
    await this.create('test_users', (table) => {
      table.increments('id').primary();
      table.string('name').notNullable();
      table.string('email').notNullable().unique();
      table.integer('age').defaultTo(0);
      table.boolean('is_active').defaultTo(true);
      table.text('bio').nullable();
      table.timestamp('created_at').nullable();
      table.timestamp('updated_at').nullable();
    });
  }

  /**
   * Reverse the migration (rollback changes)
   *
   * @param context - Migration context with database connection and utilities
   */
  async down(): Promise<void> {
    await this.drop('test_users');
  }
}
