import { Command, CommandRunner } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * ORM Mapping Describe Command
 *
 * Shows detailed entity mapping information including properties,
 * relationships, and database column mappings.
 *
 * @description CLI command for describing entity mappings
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 */
@Injectable()
@Command({
  name: 'orm:mapping:describe',
  arguments: '<entity>',
  description: 'Show entity mapping details',
})
export class OrmMappingDescribeCommand extends CommandRunner {
  private readonly logger = new Logger(OrmMappingDescribeCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  async run(inputs: string[]): Promise<void> {
    try {
      const [entityName] = inputs;

      if (!entityName) {
        throw new Error('Entity name is required');
      }

      this.logger.log(`Entity Mapping: ${entityName}\n`);

      const metadata = this.orm.getMetadata();
      const entity = metadata.get(entityName);

      if (!entity) {
        this.logger.error(`❌ Entity "${entityName}" not found`);
        return;
      }

      // Basic mapping
      this.logger.log('='.repeat(80));
      this.logger.log(`Class: ${entity.className}`);
      this.logger.log(`Table: ${entity.tableName}`);
      this.logger.log(`Collection: ${entity.collection}`);
      this.logger.log('='.repeat(80));

      // Properties with detailed mapping
      this.logger.log('\n📋 Property Mappings:');
      const properties = Object.values(entity.properties);
      properties.forEach((prop: any) => {
        this.logger.log(`\n  ${prop.name}:`);
        this.logger.log(`    Type: ${prop.type}`);
        this.logger.log(`    Column: ${prop.fieldNames?.[0] || prop.name}`);
        this.logger.log(`    Nullable: ${prop.nullable}`);
        this.logger.log(`    Primary: ${prop.primary}`);
        this.logger.log(`    Unique: ${prop.unique}`);
        if (prop.default) this.logger.log(`    Default: ${prop.default}`);
      });

      // Relationships
      const relations = entity.relations || [];
      if (relations.length > 0) {
        this.logger.log('\n🔗 Relationship Mappings:');
        relations.forEach((rel: any) => {
          this.logger.log(`\n  ${rel.name}:`);
          this.logger.log(`    Type: ${rel.reference || rel.kind}`);
          this.logger.log(`    Target: ${rel.type}`);
          this.logger.log(`    Owner: ${rel.owner}`);
        });
      }

      this.logger.log('\n✅ Mapping described successfully');
    } catch (error: any) {
      this.logger.error('❌ Failed to describe mapping:', error.message);
      throw error;
    }
  }
}
