import { Command, CommandRunner } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * ORM Debug Command
 *
 * Shows detailed debugging information about MikroORM state including
 * configuration, entities, connections, and runtime diagnostics.
 *
 * @description CLI command for debugging ORM issues
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 */
@Injectable()
@Command({
  name: 'orm:debug',
  description: 'Show ORM debug information',
})
export class OrmDebugCommand extends CommandRunner {
  private readonly logger = new Logger(OrmDebugCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  async run(): Promise<void> {
    try {
      this.logger.log('MikroORM Debug Information:\n');

      const config = this.orm.config;
      const metadata = this.orm.getMetadata();
      const connection = this.orm.em.getConnection();

      // Configuration
      this.logger.log('='.repeat(80));
      this.logger.log('CONFIGURATION');
      this.logger.log('='.repeat(80));
      this.logger.log(`Driver: ${config.get('type' as any)}`);
      this.logger.log(`Database: ${config.get('dbName')}`);
      this.logger.log(`Host: ${config.get('host')}:${config.get('port')}`);
      this.logger.log(`Debug Mode: ${config.get('debug')}`);
      this.logger.log(`Pool: Min=${config.get('pool')?.min}, Max=${config.get('pool')?.max}`);

      // Entities
      this.logger.log('\n' + '='.repeat(80));
      this.logger.log('ENTITIES');
      this.logger.log('='.repeat(80));
      const entities = Object.values(metadata.getAll());
      this.logger.log(`Total Entities: ${entities.length}`);
      entities.forEach((entity: any) => {
        this.logger.log(`  - ${entity.className} -> ${entity.tableName}`);
      });

      // Connection Status
      this.logger.log('\n' + '='.repeat(80));
      this.logger.log('CONNECTION');
      this.logger.log('='.repeat(80));
      try {
        await connection.execute('SELECT 1');
        this.logger.log('Status: ✅ Connected');
      } catch (error: any) {
        this.logger.log('Status: ❌ Disconnected');
        this.logger.log(`Error: ${error.message}`);
      }

      // Platform Info
      this.logger.log('\n' + '='.repeat(80));
      this.logger.log('PLATFORM');
      this.logger.log('='.repeat(80));
      const platform =
        (this.orm as any).config.driver?.getPlatform?.() || (this.orm as any).em.getPlatform();
      if (platform) {
        this.logger.log(`Name: ${platform.constructor.name}`);
        this.logger.log(`Supports Transactions: ${platform.supportsTransactions?.() ?? 'Unknown'}`);
      }

      this.logger.log('\n✅ Debug information displayed');
    } catch (error: any) {
      this.logger.error('❌ Failed to show debug info:', error.message);
      throw error;
    }
  }
}
