import { Command, CommandRunner } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * ORM Info Command
 *
 * Displays MikroORM configuration and runtime information.
 *
 * @description CLI command for showing ORM configuration
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 */
@Injectable()
@Command({
  name: 'orm:info',
  description: 'Show ORM configuration',
})
export class OrmInfoCommand extends CommandRunner {
  private readonly logger = new Logger(OrmInfoCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  async run(): Promise<void> {
    try {
      this.logger.log('MikroORM Configuration:\n');

      const config = this.orm.config;

      this.logger.log('='.repeat(60));
      this.logger.log(`Type: ${config.get('type' as any)}`);
      this.logger.log(`Database: ${config.get('dbName')}`);
      this.logger.log(`Debug: ${config.get('debug')}`);
      this.logger.log(`Discovery: ${config.get('discovery')?.warnWhenNoEntities}`);
      this.logger.log('='.repeat(60));

      const metadata = this.orm.getMetadata();
      this.logger.log(`\nEntities: ${metadata.getAll().size}`);

      this.logger.log('\n✅ ORM information displayed');
    } catch (error: any) {
      this.logger.error('❌ Failed to show ORM info:', error.message);
      throw error;
    }
  }
}
