import { Injectable, Logger } from '@nestjs/common';
import { Command, CommandRunner } from 'nest-commander';

/**
 * Database Seed List Command
 *
 * Displays a list of all available seeder classes in the application.
 * Shows seeder names, priorities, descriptions, and dependencies to help
 * developers understand the seeding structure and execution order.
 *
 * This command is useful for:
 * - Discovering available seeders
 * - Understanding seeder dependencies and execution order
 * - Debugging seeder priority conflicts
 * - Planning database seeding strategy
 * - Documentation and reference
 *
 * The output includes:
 * - Seeder class name
 * - Execution priority (lower runs first)
 * - Description/purpose
 * - Dependencies on other seeders
 * - Allowed environments
 *
 * @description CLI command for listing all database seeders
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```bash
 * # List all available seeders
 * npm run console db:seed:list
 *
 * # Output example:
 * # Available Seeders:
 * # 1. RoleSeeder (priority: 1)
 * #    Description: Seeds user roles
 * #    Dependencies: None
 * # 2. UserSeeder (priority: 10)
 * #    Description: Seeds test users
 * #    Dependencies: RoleSeeder
 * ```
 */
@Injectable()
@Command({
  name: 'db:seed:list',
  description: 'List all available database seeders',
})
export class DbSeedListCommand extends CommandRunner {
  private readonly logger = new Logger(DbSeedListCommand.name);

  async run(): Promise<void> {}
}
