import { Command, CommandRunner, Option } from 'nest-commander';
import { Injectable, Logger } from '@nestjs/common';
import { ModuleRef } from '@nestjs/core';
import { EntityManager } from '@mikro-orm/core';
import { FactoryManager } from '@/factories/factory.manager';
import { ISeederContext } from '@/interfaces';

/**
 * Database Seed Rollback Command
 *
 * Rolls back the last batch of executed seeders by calling their rollback()
 * methods. This command is useful for cleaning up test data or reverting
 * seeding operations during development.
 *
 * Important: Only seeders that implement the rollback() method can be
 * rolled back. Seeders without rollback methods will be skipped with a warning.
 *
 * Use cases:
 * - Cleaning up test data after testing
 * - Reverting accidentally run seeders
 * - Resetting database to previous state
 * - Development and debugging workflows
 * - Preparing for fresh seeding
 *
 * @description CLI command for rolling back database seeders
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```bash
 * # Rollback the last batch of seeders
 * npm run console db:seed:rollback
 *
 * # Rollback specific seeder
 * npm run console db:seed:rollback --class=UserSeeder
 *
 * # Rollback with verbose output
 * npm run console db:seed:rollback --verbose
 * ```
 */
@Injectable()
@Command({
  name: 'db:seed:rollback',
  description: 'Rollback the last batch of database seeders',
})
export class DbSeedRollbackCommand extends CommandRunner {
  private readonly logger = new Logger(DbSeedRollbackCommand.name);

  constructor(
    private readonly moduleRef: ModuleRef,
    private readonly em: EntityManager,
    private readonly factoryManager: FactoryManager,
  ) {
    super();
  }

  /**
   * Execute the db:seed:rollback command
   *
   * This method rolls back seeders by:
   * 1. Identifying the last batch of executed seeders
   * 2. Retrieving seeder instances from DI container
   * 3. Calling rollback() method on each seeder (if exists)
   * 4. Tracking rollback results and failures
   * 5. Updating seeder execution history
   *
   * The rollback process runs in reverse priority order (highest first)
   * to properly handle dependencies between seeders.
   *
   * @param inputs - Command arguments
   * @param options - Command options (class, verbose)
   * @returns Promise that resolves when rollback is complete
   * @throws Error if rollback fails
   *
   * @example
   * ```typescript
   * // Rollback will call the rollback() method of each seeder:
   * // await userSeeder.rollback();
   * // await roleSeeder.rollback();
   * ```
   */
  async run(inputs: string[], options?: DbSeedRollbackOptions): Promise<void> {
    try {
      const environment = process.env.NODE_ENV || 'development';
      
      this.logger.log(`Rolling back seeders in ${environment} environment...`);

      // Create seeder context
      const context: ISeederContext = {
        environment,
        args: {},
        verbose: options?.verbose ?? false,
        force: false,
      };

      // If specific seeder class is specified
      if (options?.class) {
        await this.rollbackSpecificSeeder(options.class, context);
      } else {
        await this.rollbackAllSeeders(context);
      }

      this.logger.log('✅ Seeder rollback completed successfully');
    } catch (error: any) {
      this.logger.error('❌ Rollback failed:', error.message);
      throw error;
    }
  }

  /**
   * Rollback a specific seeder class
   *
   * @param className - The seeder class name
   * @param context - Seeder execution context
   * @returns Promise that resolves when rollback is complete
   * @private
   */
  private async rollbackSpecificSeeder(
    className: string,
    context: ISeederContext,
  ): Promise<void> {
    this.logger.log(`Rolling back seeder: ${className}`);

    try {
      // Try to get the seeder from the module container
      const SeederClass = await this.getSeederClass(className);
      
      if (!SeederClass) {
        throw new Error(`Seeder ${className} not found`);
      }

      // Create seeder instance
      const seeder = new SeederClass(
        this.em,
        this.factoryManager,
        context,
      );

      // Check if seeder has rollback method
      if (typeof seeder.rollback !== 'function') {
        this.logger.warn(`⚠️  ${className} does not implement rollback() method`);
        return;
      }

      // Execute the rollback
      await seeder.rollback();

      this.logger.log(`✓ ${className} rolled back successfully`);
    } catch (error: any) {
      this.logger.error(`Failed to rollback ${className}:`, error.message);
      throw error;
    }
  }

  /**
   * Rollback all seeders in the last batch
   *
   * @param context - Seeder execution context
   * @returns Promise that resolves when all rollbacks are complete
   * @private
   */
  private async rollbackAllSeeders(context: ISeederContext): Promise<void> {
    this.logger.log('Rolling back all seeders...');
    
    // TODO: Implement batch rollback
    // This requires:
    // - Tracking seeder execution history
    // - Identifying the last batch
    // - Running rollbacks in reverse order
    
    this.logger.warn(
      '⚠️  Automatic batch rollback not yet implemented. Use --class to rollback specific seeders.',
    );
  }

  /**
   * Get seeder class by name from DI container
   *
   * @param className - The seeder class name
   * @returns The seeder class or null if not found
   * @private
   */
  private async getSeederClass(className: string): Promise<any> {
    try {
      return this.moduleRef.get(className, { strict: false });
    } catch {
      this.logger.warn(`Could not find ${className} in DI container`);
      return null;
    }
  }

  // @ts-ignore - nest-commander decorator signature mismatch
  @Option({
    flags: '--class <className>',
    description: 'The name of the seeder class to rollback',
  })
  parseClass(val: string): string {
    return val;
  }

  // @ts-ignore - nest-commander decorator signature mismatch
  @Option({
    flags: '--verbose',
    description: 'Enable verbose output',
  })
  parseVerbose(): boolean {
    return true;
  }
}

/**
 * Command options interface
 */
interface DbSeedRollbackOptions {
  /** Specific seeder class to rollback */
  class?: string;
  /** Enable verbose logging */
  verbose?: boolean;
}
