import { Injectable, Logger } from '@nestjs/common';
import { Command, CommandRunner } from 'nest-commander';

/**
 * Database Seed Command
 *
 * Runs database seeders to populate the database with data.
 * Similar to Laravel's `php artisan db:seed`.
 *
 * @description CLI command for running database seeders
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Run all seeders
 * npm run console db:seed
 *
 * # Run specific seeder
 * npm run console db:seed --class=UserSeeder
 *
 * # Run with verbose output
 * npm run console db:seed --verbose
 *
 * # Force run in production
 * npm run console db:seed --force
 * ```
 */
@Injectable()
@Command({
  name: 'db:seed',
  description: 'Seed the database with records',
})
export class DbSeedCommand extends CommandRunner {
  private readonly logger = new Logger(DbSeedCommand.name);
  async run(): Promise<void> {}
}
