import { ApiOperationOptions } from '@nestjs/swagger';
import { generateOperationId, extractTags } from './path-parser.util';

/**
 * Generates a human-readable summary from method and path.
 *
 * Creates a descriptive summary based on HTTP method and resource name.
 * Uses standard patterns for common operations.
 *
 * @param method - HTTP method
 * @param path - URL path
 * @returns Human-readable summary
 *
 * @example
 * ```typescript
 * const summary = generateSummary('GET', '/users');
 * // Returns: 'Get users'
 * ```
 *
 * @example
 * ```typescript
 * const summary = generateSummary('POST', '/posts');
 * // Returns: 'Create posts'
 * ```
 */
export function generateSummary(method: string, path: string): string {
  // Extract resource name from path
  const segments = path.split('/').filter(Boolean);
  const resource = segments[0] || 'resource';

  // Check if path contains ID parameter
  const hasId = path.includes(':id') || path.includes(':');

  // Check if this is a nested resource
  const nonParamSegments = segments.filter((seg) => !seg.startsWith(':'));
  const isNested = nonParamSegments.length > 1;

  // Generate context-aware summaries
  const summaryMap: Record<string, string> = {
    GET: hasId
      ? `Get ${resource} by ID`
      : isNested
        ? `List ${nonParamSegments[nonParamSegments.length - 1]}`
        : `List ${resource}`,
    POST: isNested
      ? `Create ${nonParamSegments[nonParamSegments.length - 1]}`
      : `Create new ${resource}`,
    PUT: hasId ? `Update ${resource} completely` : `Replace all ${resource}`,
    PATCH: hasId
      ? `Partially update ${resource}`
      : `Update multiple ${resource}`,
    DELETE: hasId ? `Delete ${resource}` : `Delete all ${resource}`,
    OPTIONS: `Get ${resource} options`,
    HEAD: `Get ${resource} headers`,
  };

  // Return mapped summary or default
  return summaryMap[method.toUpperCase()] || `${method} ${resource}`;
}

/**
 * Auto-generates documentation options for an endpoint.
 *
 * Fills in missing documentation fields with auto-generated values
 * based on HTTP method and path. Preserves any explicitly provided values.
 *
 * Generated fields:
 * - operationId: Unique identifier for the operation (e.g., 'getUsers')
 * - tags: Array of tags for grouping (e.g., ['users'])
 * - summary: Brief description of the operation (e.g., 'Get users')
 *
 * @param method - HTTP method
 * @param path - URL path
 * @param existingDocs - Existing documentation options (optional)
 * @returns Complete documentation options
 *
 * @example
 * ```typescript
 * const docs = autoGenerateDocs('GET', '/users');
 * // {
 * //   operationId: 'getUsers',
 * //   tags: ['users'],
 * //   summary: 'Get users'
 * // }
 * ```
 *
 * @example
 * With existing docs:
 * ```typescript
 * const docs = autoGenerateDocs('POST', '/users', {
 *   summary: 'Create a new user account'
 * });
 * // {
 * //   operationId: 'createUsers',
 * //   tags: ['users'],
 * //   summary: 'Create a new user account' // Preserved
 * // }
 * ```
 */
export function autoGenerateDocs(
  method: string,
  path: string,
  existingDocs?: ApiOperationOptions,
): ApiOperationOptions {
  // Start with existing docs or empty object
  const docs: ApiOperationOptions = existingDocs || {};

  // Generate operation ID if not provided
  if (!docs.operationId) {
    const operationId = generateOperationId(method, path);
    docs.operationId = operationId;
  }

  // Generate tags if not provided or empty
  if (!docs.tags || docs.tags.length === 0) {
    const tags = extractTags(path);
    docs.tags = tags;
  }

  // Generate summary if not provided
  if (!docs.summary) {
    docs.summary = generateSummary(method, path);
  }

  return docs;
}

/**
 * Enhances documentation with preset-specific information.
 *
 * Adds preset type as a tag when using preset configurations.
 * Helps organize endpoints by operation type in documentation.
 *
 * @param docs - Documentation options to enhance
 * @param preset - Preset identifier (e.g., 'crud.list')
 * @returns Enhanced documentation options
 *
 * @example
 * ```typescript
 * const docs = enhanceDocsWithPreset(
 *   { tags: ['users'], summary: 'List users' },
 *   'crud.list'
 * );
 * // {
 * //   tags: ['users', 'crud'],
 * //   summary: 'List users'
 * // }
 * ```
 */
export function enhanceDocsWithPreset(
  docs: ApiOperationOptions,
  preset: string,
): ApiOperationOptions {
  // Extract preset category (e.g., 'crud' from 'crud.list')
  const presetParts = preset.split('.');

  if (presetParts.length > 1) {
    const presetCategory = presetParts[0];

    // Add preset category as tag if not already present
    if (presetCategory) {
      const tags = docs.tags || [];
      if (!tags.includes(presetCategory)) {
        docs.tags = [...tags, presetCategory];
      }
    }
  }

  return docs;
}
