import { Command, Group } from '@nesvel/nestjs-console';
import { CommandRunner } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Entity Show Command
 *
 * Displays detailed information about a specific entity including
 * properties, relationships, indexes, and configuration.
 *
 * @description CLI command for showing entity details
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```bash
 * # Show User entity details
 * npm run console entity:show User
 * ```
 */
@Injectable()
@Command({
  name: 'entity:show',
  arguments: '<name>',
  description: 'Show detailed information about an entity',
})
@Group('Entity Inspection')
export class EntityShowCommand extends CommandRunner {
  private readonly logger = new Logger(EntityShowCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  /**
   * Execute the entity:show command
   *
   * Displays comprehensive entity information including:
   * - Entity and table names
   * - All properties with types
   * - Primary keys
   * - Relationships (OneToMany, ManyToOne, etc.)
   * - Indexes and unique constraints
   * - Lifecycle hooks
   *
   * @param inputs - Command arguments (entity name)
   * @returns Promise that resolves when complete
   */
  async run(inputs: string[]): Promise<void> {
    try {
      const [entityName] = inputs;

      if (!entityName) {
        throw new Error('Entity name is required');
      }

      this.logger.log(`Showing details for entity: ${entityName}\n`);

      const metadata = this.orm.getMetadata();
      const entity = metadata.get(entityName);

      if (!entity) {
        this.logger.error(`❌ Entity "${entityName}" not found`);
        this.logger.log('\n💡 Use "entity:list" to see all available entities');
        return;
      }

      // Basic info
      this.logger.log('='.repeat(80));
      this.logger.log(`Entity: ${entity.className}`);
      this.logger.log(`Table: ${entity.tableName}`);
      this.logger.log(`Collection: ${entity.collection}`);
      this.logger.log('='.repeat(80));

      // Properties
      this.logger.log('\n📋 Properties:');
      const properties = Object.values(entity.properties);
      properties.forEach((prop: any) => {
        this.logger.log(`  - ${prop.name}: ${prop.type} ${prop.primary ? '(PRIMARY)' : ''}`);
      });

      // Relationships
      const relationships = entity.relations;
      if (relationships && relationships.length > 0) {
        this.logger.log('\n🔗 Relationships:');
        relationships.forEach((rel: any) => {
          this.logger.log(`  - ${rel.name}: ${rel.kind} -> ${rel.type}`);
        });
      }

      // Indexes
      if (entity.indexes && entity.indexes.length > 0) {
        this.logger.log('\n🔍 Indexes:');
        entity.indexes.forEach((idx: any) => {
          const props = Array.isArray(idx.properties) ? idx.properties.join(', ') : idx.properties;
          this.logger.log(`  - ${idx.name || 'unnamed'}: ${props}`);
        });
      }

      this.logger.log('\n✅ Entity details displayed successfully');
    } catch (error: any) {
      this.logger.error('❌ Failed to show entity:', error.message);
      throw error;
    }
  }
}
