import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';
import { randomBytes } from 'crypto';

/**
 * Custom Headers Middleware
 *
 * Adds custom application headers to all responses for identification,
 * debugging, and monitoring purposes.
 *
 * @description
 * Custom headers added:
 * - X-Server-ID: Unique server identifier
 * - X-App-Version: Application version
 * - X-Environment: Deployment environment
 * - X-Region: Server region/data center
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 */
@Injectable()
export class CustomHeadersMiddleware implements NestMiddleware {
  private readonly serverId = randomBytes(8).toString('hex');
  private readonly appVersion = process.env.APP_VERSION || '1.0.0';
  private readonly environment = process.env.NODE_ENV || 'development';
  private readonly region = process.env.AWS_REGION || process.env.REGION || 'local';

  use(req: Request, res: Response, next: NextFunction): void {
    // Add server identification
    res.setHeader('X-Server-ID', this.serverId);

    // Add application version
    res.setHeader('X-App-Version', this.appVersion);

    // Add environment (only in non-production)
    if (this.environment !== 'production') {
      res.setHeader('X-Environment', this.environment);
    }

    // Add region/data center
    res.setHeader('X-Region', this.region);

    next();
  }
}
