import { Module } from '@nestjs/common';
import { OrmModule } from '@nesvel/nestjs-orm';
import { Product } from '@/entities/product';
import { ProductRepository } from '@/repositories/product.repository';
import { ProductService } from '@/services/product.service';
import { ProductController } from '@/controllers/product.controller';

/**
 * Productmodule Module
 *
 * @description Module for Product feature
 * @author Generated by @nesvel/nestjs-orm
 */
@Module({
  imports: [
    OrmModule.forFeature([Product]),
  ],
  controllers: [ProductController],
  providers: [
    ProductRepository,
    ProductService,
  ],
  exports: [
    ProductService,
  ],
})
export class Productmodule {}
