import { Entity, Property, BaseEntity, Enum } from '@nesvel/nestjs-orm';

/**
 * Order Status Enum
 */
export enum OrderStatus {
  PENDING = 'pending',
  PROCESSING = 'processing',
  SHIPPED = 'shipped',
  DELIVERED = 'delivered',
  CANCELLED = 'cancelled',
}

/**
 * Payment Method Enum
 */
export enum PaymentMethod {
  CREDIT_CARD = 'credit_card',
  PAYPAL = 'paypal',
  BANK_TRANSFER = 'bank_transfer',
  CASH = 'cash',
}

/**
 * Order Entity
 *
 * Represents a customer order with comprehensive tracking information,
 * payment details, shipping information, and polymorphic relations.
 *
 * @description Generated model with all column types
 * @extends BaseEntity
 * @author Generated by @nesvel/nestjs-orm
 *
 * @remarks
 * To use a custom repository, replace the decorator with:
 * @Entity({ repository: () => OrderRepository })
 *
 * This enables type-safe access via em.getRepository(Order) and
 * allows you to add custom query methods to OrderRepository.
 *
 * @see https://mikro-orm.io/docs/repositories#inferring-custom-repository-type
 */
@Entity({ tableName: 'orders' })
export class Order extends BaseEntity {
  // ============================================================================
  // STRING FIELDS
  // ============================================================================

  /**
   * Unique order number
   */
  @Property({ type: 'string', length: 50, unique: true })
  orderNumber!: string;

  /**
   * Customer email address
   */
  @Property({ type: 'string' })
  customerEmail!: string;

  /**
   * Order notes
   */
  @Property({ type: 'text', nullable: true })
  notes?: string;

  /**
   * Long description (LONGTEXT)
   */
  @Property({ type: 'text', nullable: true })
  longDescription?: string;

  /**
   * Status code (3 character)
   */
  @Property({ type: 'char', length: 3, default: 'PEN' })
  statusCode!: string;

  // ============================================================================
  // NUMERIC FIELDS
  // ============================================================================

  /**
   * Order quantity
   */
  @Property({ type: 'integer', default: 1 })
  quantity!: number;

  /**
   * Tracking number
   */
  @Property({ type: 'bigint', nullable: true })
  trackingNumber?: string;

  /**
   * Subtotal amount
   */
  @Property({ type: 'decimal', precision: 10, scale: 2, default: '0' })
  subtotal!: string;

  /**
   * Tax amount
   */
  @Property({ type: 'decimal', precision: 10, scale: 2, default: '0' })
  tax!: string;

  /**
   * Total amount
   */
  @Property({ type: 'decimal', precision: 10, scale: 2 })
  total!: string;

  /**
   * Discount percentage
   */
  @Property({ type: 'float', nullable: true })
  discountPercentage?: number;

  /**
   * Order priority
   */
  @Property({ type: 'integer', unsigned: true, default: 0 })
  priority!: number;

  // ============================================================================
  // BOOLEAN FIELDS
  // ============================================================================

  /**
   * Payment status
   */
  @Property({ type: 'boolean', default: false })
  isPaid!: boolean;

  /**
   * Shipping status
   */
  @Property({ type: 'boolean', default: false })
  isShipped!: boolean;

  /**
   * Gift order flag
   */
  @Property({ type: 'boolean', default: false })
  isGift!: boolean;

  // ============================================================================
  // DATE & TIME FIELDS
  // ============================================================================

  /**
   * Order date
   */
  @Property({ type: 'date' })
  orderDate!: Date;

  /**
   * Shipping timestamp
   */
  @Property({ type: 'datetime', nullable: true })
  shippedAt?: Date;

  /**
   * Payment timestamp
   */
  @Property({ type: 'datetime', nullable: true })
  paidAt?: Date;

  /**
   * Cancellation timestamp
   */
  @Property({ type: 'datetime', nullable: true })
  cancelledAt?: Date;

  // ============================================================================
  // BINARY FIELDS
  // ============================================================================

  /**
   * Digital signature data
   */
  @Property({ type: 'blob', nullable: true })
  signatureData?: Buffer;

  // ============================================================================
  // JSON FIELDS
  // ============================================================================

  /**
   * Shipping address (JSON)
   */
  @Property({ type: 'json', nullable: true })
  shippingAddress?: {
    street: string;
    city: string;
    state: string;
    zipCode: string;
    country: string;
  };

  /**
   * Billing address (JSON)
   */
  @Property({ type: 'json', nullable: true })
  billingAddress?: {
    street: string;
    city: string;
    state: string;
    zipCode: string;
    country: string;
  };

  /**
   * Additional metadata (JSON)
   */
  @Property({ type: 'json', nullable: true })
  metadata?: Record<string, any>;

  // ============================================================================
  // UUID FIELDS
  // ============================================================================

  /**
   * External system ID (UUID)
   */
  @Property({ type: 'uuid', unique: true })
  externalId!: string;

  // ============================================================================
  // ENUM FIELDS
  // ============================================================================

  /**
   * Order status
   */
  @Enum({ items: () => OrderStatus, default: OrderStatus.PENDING })
  status!: OrderStatus;

  /**
   * Payment method
   */
  @Enum({ items: () => PaymentMethod, nullable: true })
  paymentMethod?: PaymentMethod;

  // ============================================================================
  // FOREIGN KEY FIELDS
  // ============================================================================

  /**
   * User ID (foreign key)
   */
  @Property({ type: 'bigint', unsigned: true, nullable: true })
  userId?: string;

  /**
   * Shipping method ID (foreign key)
   */
  @Property({ type: 'bigint', unsigned: true, nullable: true })
  shippingMethodId?: string;

  // ============================================================================
  // NETWORK FIELDS
  // ============================================================================

  /**
   * Customer IP address
   */
  @Property({ type: 'string', nullable: true })
  customerIp?: string;

  // ============================================================================
  // POLYMORPHIC RELATION FIELDS
  // ============================================================================

  /**
   * Trackable type (polymorphic)
   */
  @Property({ type: 'string', nullable: true })
  trackableType?: string;

  /**
   * Trackable ID (polymorphic)
   */
  @Property({ type: 'bigint', unsigned: true, nullable: true })
  trackableId?: string;

  // ============================================================================
  // SPECIAL FIELDS
  // ============================================================================

  /**
   * Remember token for stateless sessions
   */
  @Property({ type: 'string', length: 100, nullable: true })
  rememberToken?: string;

  // ============================================================================
  // CUSTOM METHODS
  // ============================================================================

  /**
   * Check if order is completed
   */
  isCompleted(): boolean {
    return this.status === OrderStatus.DELIVERED;
  }

  /**
   * Check if order can be cancelled
   */
  canBeCancelled(): boolean {
    return [
      OrderStatus.PENDING,
      OrderStatus.PROCESSING,
    ].includes(this.status);
  }

  /**
   * Calculate final amount after discount
   */
  getFinalAmount(): number {
    const total = parseFloat(this.total);
    if (this.discountPercentage) {
      return total * (1 - this.discountPercentage / 100);
    }
    return total;
  }

  /**
   * Get full address string
   */
  getShippingAddressString(): string | null {
    if (!this.shippingAddress) return null;
    const addr = this.shippingAddress;
    return `${addr.street}, ${addr.city}, ${addr.state} ${addr.zipCode}, ${addr.country}`;
  }
}
