import { Entity, Property, BaseEntity } from '@nesvel/nestjs-orm';

/**
 * Order Entity
 *
 * @description Generated model
 * @extends BaseEntity
 * @author Generated by @nesvel/nestjs-orm
 *
 * @remarks
 * To use a custom repository, replace the decorator with:
 * @Entity({ repository: () => OrderRepository })
 *
 * This enables type-safe access via em.getRepository(Order) and
 * allows you to add custom query methods to OrderRepository.
 *
 * @see https://mikro-orm.io/docs/repositories#inferring-custom-repository-type
 */
@Entity()
export class Order extends BaseEntity {
  /**
   * Name property
   */
  @Property()
  name!: string;

  /**
   * Add your custom properties here
   *
   * @example
   * @Property()
   * email!: string;
   *
   * @Property({ type: 'text', nullable: true })
   * description?: string;
   *
   * @Property({ default: true })
   * isActive!: boolean;
   */

  /**
   * Add relationships here
   *
   * @example
   * @ManyToOne(() => User)
   * user!: User;
   *
   * @OneToMany(() => Post, post => post.author)
   * posts = new Collection<Post>(this);
   */

  /**
   * Add custom methods here
   *
   * @example
   * getFullName(): string {
   *   return `${this.firstName} ${this.lastName}`;
   * }
   */
}
