import { Command, CommandRunner } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Entity List Command
 *
 * Lists all registered entities in the application with their metadata.
 * Displays entity names, table names, and basic configuration information.
 *
 * Use this command for:
 * - Discovering available entities
 * - Verifying entity registration
 * - Understanding entity-table mappings
 * - Debugging entity loading issues
 * - Documentation and reference
 *
 * @description CLI command for listing all registered entities
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```bash
 * # List all entities
 * npm run console entity:list
 * ```
 */
@Injectable()
@Command({
  name: 'entity:list',
  description: 'List all registered entities',
})
export class EntityListCommand extends CommandRunner {
  private readonly logger = new Logger(EntityListCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  /**
   * Execute the entity:list command
   *
   * This method lists all entities by:
   * 1. Accessing the MikroORM metadata registry
   * 2. Iterating through all entity metadata
   * 3. Extracting entity names and table names
   * 4. Displaying in a formatted table
   * 5. Showing entity count summary
   *
   * @returns Promise that resolves when listing is complete
   */
  async run(): Promise<void> {
    try {
      this.logger.log('Listing all registered entities...\n');

      const metadata = this.orm.getMetadata();
      const entities = metadata.getAll();
      const entityArray = Object.values(entities);

      if (entityArray.length === 0) {
        this.logger.warn('⚠️  No entities found');
        this.logger.log('Make sure your entities are properly registered in MikroORM configuration');
        return;
      }

      // Display header
      this.logger.log('='.repeat(80));
      this.logger.log(
        'Entity Name'.padEnd(30) +
        'Table Name'.padEnd(30) +
        'Properties'.padEnd(10)
      );
      this.logger.log('='.repeat(80));

      // Display each entity
      entityArray.forEach((entity: any) => {
        const entityName = entity.className;
        const tableName = entity.tableName;
        const properties = entity.props || entity.properties || {};
        const propertyCount = Array.isArray(properties) ? properties.length : Object.keys(properties).length;

        this.logger.log(
          entityName.padEnd(30) +
          tableName.padEnd(30) +
          propertyCount.toString().padEnd(10)
        );
      });

      this.logger.log('='.repeat(80));
      this.logger.log(`\n✅ Total entities: ${entityArray.length}`);
      
      this.logger.log('\n💡 Use "entity:show <EntityName>" to see detailed information');
    } catch (error: any) {
      this.logger.error('❌ Failed to list entities:', error.message);
      throw error;
    }
  }
}
