import { Command, Group } from '@nesvel/nestjs-console';
import { CommandRunner, Option } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Schema Drop Command
 *
 * Drops all database tables.
 * Similar to Laravel's `php artisan db:wipe`.
 *
 * WARNING: This command will destroy all data in the database!
 *
 * @description CLI command for dropping database schema
 * @author Generated by @nesvel/nestjs-orm
 *
 * @example
 * ```bash
 * # Drop all tables
 * npm run console schema:drop
 *
 * # Drop tables including migrations table
 * npm run console schema:drop --drop-migrations-table
 * ```
 */
@Injectable()
@Command({
  name: 'schema:drop',
  description: 'Drop all database tables',
})
@Group('Schema Management')
export class SchemaDropCommand extends CommandRunner {
  private readonly logger = new Logger(SchemaDropCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  async run(inputs: string[], options?: SchemaDropOptions): Promise<void> {
    try {
      const schemaGenerator = this.orm.getSchemaGenerator();

      this.logger.warn('⚠️  WARNING: This will drop all tables and destroy all data!');
      this.logger.log('Dropping database schema...');

      await schemaGenerator.dropSchema({
        dropMigrationsTable: options?.dropMigrationsTable ?? false,
        dropDb: false,
      });

      this.logger.log('✅ Database schema dropped successfully');
    } catch (error: any) {
      this.logger.error('❌ Failed to drop schema:', error.message);
      throw error;
    }
  }

  // @ts-ignore - nest-commander decorator signature mismatch
  @Option({
    flags: '--drop-migrations-table',
    description: 'Also drop the migrations table',
  })
  parseDropMigrationsTable(): boolean {
    return true;
  }
}

interface SchemaDropOptions {
  dropMigrationsTable?: boolean;
}
