import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';

/**
 * CORS Middleware
 *
 * Handles Cross-Origin Resource Sharing (CORS) to control which domains
 * can access your API. This is essential for frontend applications running
 * on different domains/ports than your API.
 *
 * @description
 * CORS headers managed:
 * - Access-Control-Allow-Origin: Specifies allowed origins
 * - Access-Control-Allow-Methods: Specifies allowed HTTP methods
 * - Access-Control-Allow-Headers: Specifies allowed request headers
 * - Access-Control-Allow-Credentials: Allows cookies/auth headers
 * - Access-Control-Max-Age: Caches preflight requests
 *
 * @features
 * - Configurable allowed origins (whitelist or wildcard)
 * - Support for credentials (cookies, authorization headers)
 * - Preflight request handling (OPTIONS method)
 * - Custom headers support
 * - Environment-based configuration
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(CorsMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 *
 * @example Environment configuration
 * ```env
 * # Allow all origins (development only)
 * CORS_ORIGIN=*
 *
 * # Allow specific origins (production)
 * CORS_ORIGIN=https://app.example.com,https://admin.example.com
 * ```
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
 */
@Injectable()
export class CorsMiddleware implements NestMiddleware {
  /**
   * Allowed origins for CORS requests
   * Can be a comma-separated list or '*' for all origins
   *
   * @private
   */
  private readonly allowedOrigins: string[];

  /**
   * Whether to allow credentials (cookies, authorization headers)
   *
   * @private
   */
  private readonly allowCredentials: boolean;

  constructor() {
    // Get allowed origins from environment variable
    const originsEnv = process.env.CORS_ORIGIN || '*';

    // Parse origins - split by comma if multiple, otherwise use as-is
    this.allowedOrigins = originsEnv === '*' ? ['*'] : originsEnv.split(',').map((o) => o.trim());

    // Allow credentials if not using wildcard origin
    // Note: Credentials cannot be used with wildcard origin (security restriction)
    this.allowCredentials = this.allowedOrigins[0] !== '*';
  }

  /**
   * Apply CORS headers to responses
   *
   * @param req - Express request object
   * @param res - Express response object
   * @param next - Next function to call
   */
  use(req: Request, res: Response, next: NextFunction): void {
    const origin = req.headers.origin;

    // Check if origin is allowed
    if (this.isOriginAllowed(origin)) {
      // Set allowed origin (either specific origin or *)
      res.setHeader(
        'Access-Control-Allow-Origin',
        this.allowedOrigins[0] === '*' ? '*' : origin || '*'
      );

      // Allow credentials if configured
      if (this.allowCredentials) {
        res.setHeader('Access-Control-Allow-Credentials', 'true');
      }

      // Set allowed methods
      res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD');

      // Set allowed headers
      res.setHeader(
        'Access-Control-Allow-Headers',
        [
          'Content-Type',
          'Authorization',
          'X-Requested-With',
          'X-Request-ID',
          'X-Correlation-ID',
          'X-Trace-ID',
          'X-API-Version',
          'X-Tenant-ID',
          'Accept',
          'Accept-Language',
          'Origin',
        ].join(', ')
      );

      // Set exposed headers (headers that client can read)
      res.setHeader(
        'Access-Control-Expose-Headers',
        [
          'X-Request-ID',
          'X-Correlation-ID',
          'X-Trace-ID',
          'X-Response-Time',
          'X-RateLimit-Limit',
          'X-RateLimit-Remaining',
          'X-RateLimit-Reset',
        ].join(', ')
      );

      // Cache preflight requests for 24 hours
      res.setHeader('Access-Control-Max-Age', '86400');
    }

    // Handle preflight requests (OPTIONS method)
    if (req.method === 'OPTIONS') {
      // End preflight request immediately
      res.status(204).send();
      return;
    }

    next();
  }

  /**
   * Check if the origin is allowed
   *
   * @param origin - Origin from request header
   * @returns True if origin is allowed
   * @private
   */
  private isOriginAllowed(origin: string | undefined): boolean {
    // Allow if no origin header (same-origin requests)
    if (!origin) {
      return true;
    }

    // Allow if wildcard is configured
    if (this.allowedOrigins[0] === '*') {
      return true;
    }

    // Check if origin is in whitelist
    return this.allowedOrigins.includes(origin);
  }
}
