import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';

/**
 * Content Security Policy (CSP) Middleware
 *
 * Sets Content-Security-Policy headers to prevent XSS attacks by controlling
 * which resources (scripts, styles, images, etc.) can be loaded and executed.
 *
 * @description
 * CSP is a security standard that helps prevent:
 * - Cross-Site Scripting (XSS) attacks
 * - Clickjacking attacks
 * - Code injection attacks
 * - Data injection attacks
 *
 * @features
 * - Restricts script sources to same origin
 * - Blocks inline scripts and eval()
 * - Controls image, style, and font sources
 * - Prevents mixed content (HTTP resources on HTTPS pages)
 * - Configurable for API vs full web applications
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(CspMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 *
 * @example CSP Header Result
 * ```
 * Content-Security-Policy: default-src 'self'; script-src 'self'; ...
 * ```
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
 * @see https://content-security-policy.com/
 */
@Injectable()
export class CspMiddleware implements NestMiddleware {
  /**
   * CSP directives for API applications
   * Configured for strict security suitable for JSON APIs
   *
   * @private
   */
  private readonly cspDirectives: Record<string, string[]> = {
    // Default policy - fallback for all resource types
    'default-src': ["'self'"],

    // Script sources - where JavaScript can be loaded from
    // 'self' = same origin only
    'script-src': ["'self'"],

    // Style sources - where CSS can be loaded from
    'style-src': ["'self'", "'unsafe-inline'"], // unsafe-inline needed for some UI libraries

    // Image sources - where images can be loaded from
    'img-src': ["'self'", 'data:', 'https:'],

    // Font sources - where fonts can be loaded from
    'font-src': ["'self'", 'data:'],

    // Connect sources - AJAX, WebSocket, fetch() destinations
    'connect-src': ["'self'"],

    // Frame sources - where iframes can be loaded from
    'frame-src': ["'none'"],

    // Object sources - for <object>, <embed>, <applet>
    'object-src': ["'none'"],

    // Media sources - for <audio> and <video>
    'media-src': ["'self'"],

    // Worker sources - for Web Workers and Service Workers
    'worker-src': ["'self'"],

    // Form action - where forms can submit to
    'form-action': ["'self'"],

    // Frame ancestors - who can embed this page in iframe
    'frame-ancestors': ["'none'"],

    // Base URI - restricts <base> tag URLs
    'base-uri': ["'self'"],

    // Upgrade insecure requests - automatically upgrade HTTP to HTTPS
    'upgrade-insecure-requests': [],
  };

  /**
   * Apply Content Security Policy headers
   *
   * @param req - Express request object
   * @param res - Express response object
   * @param next - Next function to call
   */
  use(req: Request, res: Response, next: NextFunction): void {
    // Build CSP header value from directives
    const cspHeader = this.buildCspHeader();

    // Set the CSP header
    // Using 'Content-Security-Policy' for enforcement
    // For testing, you can use 'Content-Security-Policy-Report-Only' instead
    res.setHeader('Content-Security-Policy', cspHeader);

    next();
  }

  /**
   * Build CSP header string from directives
   *
   * @returns Formatted CSP header value
   * @private
   */
  private buildCspHeader(): string {
    const policies: string[] = [];

    // Convert directives object to CSP policy string
    for (const [directive, sources] of Object.entries(this.cspDirectives)) {
      if (sources.length === 0) {
        // Directive with no value (like upgrade-insecure-requests)
        policies.push(directive);
      } else {
        // Directive with sources
        policies.push(`${directive} ${sources.join(' ')}`);
      }
    }

    // Join all policies with semicolons
    return policies.join('; ');
  }
}
