import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';

/**
 * Helmet Middleware
 *
 * Sets various HTTP security headers to protect against common web vulnerabilities.
 * This middleware helps secure your Express/NestJS app by setting HTTP response headers.
 *
 * @description
 * Security headers set by this middleware:
 * - X-Content-Type-Options: nosniff (Prevents MIME type sniffing)
 * - X-Frame-Options: DENY (Prevents clickjacking attacks)
 * - X-XSS-Protection: 1; mode=block (Enables XSS filter in older browsers)
 * - Strict-Transport-Security: Forces HTTPS connections
 * - X-Download-Options: noopen (Prevents IE from executing downloads)
 * - X-Permitted-Cross-Domain-Policies: none (Restricts Adobe Flash/PDF cross-domain requests)
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(HelmetMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 *
 * @see https://helmetjs.github.io/
 */
@Injectable()
export class HelmetMiddleware implements NestMiddleware {
  /**
   * Apply security headers to all responses
   *
   * @param req - Express request object
   * @param res - Express response object
   * @param next - Next function to call
   */
  use(req: Request, res: Response, next: NextFunction): void {
    // Prevent MIME type sniffing
    // This header prevents browsers from trying to guess ("sniff") the MIME type
    res.setHeader('X-Content-Type-Options', 'nosniff');

    // Prevent clickjacking attacks
    // This header prevents your site from being embedded in iframes
    res.setHeader('X-Frame-Options', 'DENY');

    // Enable XSS filter in older browsers
    // Modern browsers have this enabled by default, but this provides backwards compatibility
    res.setHeader('X-XSS-Protection', '1; mode=block');

    // Force HTTPS connections (HSTS)
    // Tells browsers to only connect via HTTPS for the next year
    // Only enable this if your site is served over HTTPS
    if (process.env.NODE_ENV === 'production') {
      res.setHeader('Strict-Transport-Security', 'max-age=31536000; includeSubDomains; preload');
    }

    // Prevent IE from executing downloads in site's context
    res.setHeader('X-Download-Options', 'noopen');

    // Restrict Adobe Flash and PDF cross-domain requests
    res.setHeader('X-Permitted-Cross-Domain-Policies', 'none');

    // Referrer policy - controls how much referrer information should be included
    res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');

    // DNS prefetch control - controls browser DNS prefetching
    res.setHeader('X-DNS-Prefetch-Control', 'off');

    next();
  }
}
