import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';

/**
 * Remove Powered-By Middleware
 *
 * Removes the X-Powered-By header to hide the technology stack
 * powering the application. This is a simple security measure to
 * prevent attackers from knowing what framework you're using.
 *
 * @description
 * By default, Express.js adds an 'X-Powered-By: Express' header to all responses.
 * This middleware removes that header to avoid revealing implementation details
 * that could help attackers target specific vulnerabilities.
 *
 * @security
 * - Implements "Security through obscurity" principle
 * - Prevents disclosure of framework/runtime version
 * - Makes automated vulnerability scanning harder
 * - Recommended by OWASP security guidelines
 *
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // In app.module.ts
 * export class AppModule implements NestModule {
 *   configure(consumer: MiddlewareConsumer) {
 *     consumer
 *       .apply(RemovePoweredByMiddleware)
 *       .forRoutes('*');
 *   }
 * }
 * ```
 *
 * @example Before applying middleware
 * ```
 * HTTP/1.1 200 OK
 * X-Powered-By: Express
 * Content-Type: application/json
 * ```
 *
 * @example After applying middleware
 * ```
 * HTTP/1.1 200 OK
 * Content-Type: application/json
 * ```
 *
 * @see https://owasp.org/www-project-web-security-testing-guide/
 */
@Injectable()
export class RemovePoweredByMiddleware implements NestMiddleware {
  /**
   * Remove X-Powered-By header from response
   *
   * @param req - Express request object
   * @param res - Express response object
   * @param next - Next function to call
   */
  use(req: Request, res: Response, next: NextFunction): void {
    // Remove the X-Powered-By header if it exists
    // Express sets this by default to 'Express'
    res.removeHeader('X-Powered-By');

    next();
  }
}
