import { Injectable } from '@nestjs/common';
import { BaseSubscriber } from '@nesvel/nestjs-orm';
import { InjectPubSub, PubSubService } from '@nesvel/nestjs-pubsub';

import { Order } from '@order/entities/order.entity';

/**
 * OrderSubscriber
 *
 * Entity subscriber for Order lifecycle events.
 * Extends BaseSubscriber to automatically publish entity events to PubSub.
 *
 * This subscriber listens to Order entity lifecycle events and publishes
 * them to the PubSub system for consumption by other services. It inherits all
 * functionality from BaseSubscriber including:
 * - Automatic event publishing on create, update, delete
 * - Change tracking with before/after values
 * - Performance metrics (optional)
 * - Configurable channel naming patterns
 * - Sensitive data sanitization
 *
 * Published Events:
 * - order.created - When a new Order is created
 * - order.updated - When an existing Order is updated
 * - order.deleted - When a Order is hard deleted
 * - order.soft_deleted - When a Order is soft deleted
 * - order.loaded - When a Order is loaded (if enabled)
 *
 * @description Subscribes to and publishes Order entity events
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // Register in module:
 * @Module({
 *   providers: [OrderSubscriber],
 * })
 * export class AppModule {}
 *
 * // Listen to events in another service:
 * this.pubsub.subscribe('order.created', (payload) => {
 *   console.log('New Order created:', payload.entityId);
 *   // Send notification, update cache, etc.
 * });
 * ```
 */
@Injectable()
export class OrderSubscriber extends BaseSubscriber<Order> {
  /**
   * Constructor for OrderSubscriber
   *
   * Injects the PubSub service and configures subscriber options.
   * The parent BaseSubscriber handles all event publishing logic.
   *
   * @param pubsub - PubSub service for event publishing
   */
  constructor(@InjectPubSub() pubsubService: PubSubService) {
    super(pubsubService, {
      enabled: true, // Enable event publishing
      logEvents: false, // Disable logging to prevent spam
      publishLoadEvents: false, // Don't publish load events
      trackDetailedChanges: true, // Enable change tracking for updates
      includePerformanceMetrics: false, // Disable performance tracking
      channelPattern: '{entityName}.{operation}', // Simple channel naming
    });
  }

  /**
   * Get the entities this subscriber listens to
   *
   * Returns an array containing the Order entity class.
   * Only events from Order entities will trigger this subscriber.
   *
   * @returns Array containing Order entity class
   */
  getSubscribedEntities(): any[] {
    return [Order];
  }

  // ============================================================================
  // Note: The BaseSubscriber already handles:
  // - Publishing events to PubSub on all lifecycle events
  // - Change tracking with before/after values on updates
  // - Sensitive data sanitization
  // - Performance metrics (if enabled)
  // - Error handling that won't break database operations
  //
  // You only need to override methods if you need ADDITIONAL custom behavior
  // beyond the automatic event publishing provided by BaseSubscriber.
  // ============================================================================
}
