import {
  Controller,
  Get,
  Post,
  Put,
  Patch,
  Delete,
  Body,
  Param,
  Query,
  HttpCode,
  HttpStatus,
  ParseIntPipe,
  NotFoundException,
  BadRequestException,
  UseInterceptors,
  ClassSerializerInterceptor,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiParam,
  ApiQuery,
  ApiBody,
  ApiCreatedResponse,
  ApiOkResponse,
  ApiNotFoundResponse,
  ApiBadRequestResponse,
  ApiInternalServerErrorResponse,
} from '@nestjs/swagger';
import { ProductService } from '@/services/product.service';
import { Product } from '@/entities/product';
// import { CreateProductDto } from '@/dtos/create-product.dto';
// import { UpdateProductDto } from '@/dtos/update-product.dto';

/**
 * Productcontroller Controller
 *
 * RESTful API controller for managing Product resources.
 * Provides full CRUD operations with OpenAPI documentation.
 *
 * @description REST API controller for Product entity
 * @author Generated by @nesvel/nestjs-orm
 */
@ApiTags('products')
@Controller('products')
@UseInterceptors(ClassSerializerInterceptor)
export class Productcontroller {
  /**
   * Creates an instance of Productcontroller
   *
   * @param productService - The Product service
   */
  constructor(private readonly productService: ProductService) {}

  /**
   * Get all products with optional pagination
   *
   * Retrieves a list of all products. Supports pagination via query parameters.
   *
   * @param page - Page number (1-based)
   * @param limit - Number of items per page
   * @returns List of products or paginated result
   */
  @Get()
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Get all products',
    description: 'Retrieve a list of all products with optional pagination',
  })
  @ApiQuery({
    name: 'page',
    required: false,
    type: Number,
    description: 'Page number for pagination (1-based)',
    example: 1,
  })
  @ApiQuery({
    name: 'limit',
    required: false,
    type: Number,
    description: 'Number of items per page',
    example: 20,
  })
  @ApiOkResponse({
    description: 'List of products retrieved successfully',
    type: [Product],
  })
  @ApiInternalServerErrorResponse({
    description: 'Internal server error',
  })
  async findAll(
    @Query('page', new ParseIntPipe({ optional: true })) page?: number,
    @Query('limit', new ParseIntPipe({ optional: true })) limit?: number,
  ) {
    if (page && limit) {
      return this.productService.paginate(page, limit);
    }
    return this.productService.all();
  }

  /**
   * Get a single product by ID
   *
   * Retrieves a specific product by its unique identifier.
   *
   * @param id - The product ID
   * @returns The product entity
   * @throws NotFoundException if product not found
   */
  @Get(':id')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Get product by ID',
    description: 'Retrieve a specific product by its unique identifier',
  })
  @ApiParam({
    name: 'id',
    type: Number,
    description: 'The unique identifier of the product',
    example: 1,
  })
  @ApiOkResponse({
    description: 'Product found and retrieved successfully',
    type: Product,
  })
  @ApiNotFoundResponse({
    description: 'Product not found',
  })
  @ApiBadRequestResponse({
    description: 'Invalid ID format',
  })
  async findOne(@Param('id', ParseIntPipe) id: number) {
    try {
      return await this.productService.findOrFail(id);
    } catch (error: Error | any) {
      throw new NotFoundException(`Product with ID ${id} not found`);
    }
  }

  /**
   * Create a new product
   *
   * Creates a new product resource with the provided data.
   *
   * @param data - The product creation data
   * @returns The created product
   * @throws BadRequestException if validation fails
   */
  @Post()
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Create a new product',
    description: 'Create a new product resource with the provided data',
  })
  @ApiBody({
    description: 'Product creation data',
    // type: CreateProductDto,
    schema: {
      type: 'object',
      properties: {
        name: { type: 'string', example: 'Example Name' },
        // Add more properties based on your DTO
      },
    },
  })
  @ApiCreatedResponse({
    description: 'Product created successfully',
    type: Product,
  })
  @ApiBadRequestResponse({
    description: 'Invalid input data or validation failed',
  })
  @ApiInternalServerErrorResponse({
    description: 'Internal server error',
  })
  async create(@Body() data: Partial<Product>) {
    // TODO: Replace with DTO type after creating it
    // async create(@Body() data: CreateProductDto) {
    try {
      return await this.productService.create(data);
    } catch (error: Error | any) {
      throw new BadRequestException(
        `Failed to create product: ${error.message}`,
      );
    }
  }

  /**
   * Update an existing product (full update)
   *
   * Replaces all fields of an existing product with the provided data.
   *
   * @param id - The product ID
   * @param data - The complete updated product data
   * @returns The updated product
   * @throws NotFoundException if product not found
   * @throws BadRequestException if validation fails
   */
  @Put(':id')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Update product (full update)',
    description: 'Replace all fields of an existing product with provided data',
  })
  @ApiParam({
    name: 'id',
    type: Number,
    description: 'The unique identifier of the product',
    example: 1,
  })
  @ApiBody({
    description: 'Complete product update data',
    // type: UpdateProductDto,
    schema: {
      type: 'object',
      properties: {
        name: { type: 'string', example: 'Updated Name' },
        // Add more properties based on your DTO
      },
    },
  })
  @ApiOkResponse({
    description: 'Product updated successfully',
    type: Product,
  })
  @ApiNotFoundResponse({
    description: 'Product not found',
  })
  @ApiBadRequestResponse({
    description: 'Invalid input data or validation failed',
  })
  async update(
    @Param('id', ParseIntPipe) id: number,
    @Body() data: Partial<Product>,
    // Replace with: @Body() data: UpdateProductDto,
  ) {
    try {
      return await this.productService.update(id, data);
    } catch (error: Error | any) {
      if (error.message.includes('not found')) {
        throw new NotFoundException(`Product with ID ${id} not found`);
      }
      throw new BadRequestException(
        `Failed to update product: ${error.message}`,
      );
    }
  }

  /**
   * Partially update an existing product
   *
   * Updates only the specified fields of an existing product.
   *
   * @param id - The product ID
   * @param data - The partial product update data
   * @returns The updated product
   * @throws NotFoundException if product not found
   * @throws BadRequestException if validation fails
   */
  @Patch(':id')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Partially update product',
    description: 'Update only specified fields of an existing product',
  })
  @ApiParam({
    name: 'id',
    type: Number,
    description: 'The unique identifier of the product',
    example: 1,
  })
  @ApiBody({
    description: 'Partial product update data',
    schema: {
      type: 'object',
      properties: {
        name: { type: 'string', example: 'Updated Name' },
        // Add more properties - all optional for PATCH
      },
    },
  })
  @ApiOkResponse({
    description: 'Product updated successfully',
    type: Product,
  })
  @ApiNotFoundResponse({
    description: 'Product not found',
  })
  @ApiBadRequestResponse({
    description: 'Invalid input data or validation failed',
  })
  async partialUpdate(
    @Param('id', ParseIntPipe) id: number,
    @Body() data: Partial<Product>,
  ) {
    try {
      return await this.productService.update(id, data);
    } catch (error: Error | any) {
      if (error.message.includes('not found')) {
        throw new NotFoundException(`Product with ID ${id} not found`);
      }
      throw new BadRequestException(
        `Failed to update product: ${error.message}`,
      );
    }
  }

  /**
   * Delete a product
   *
   * Permanently deletes a product from the database.
   *
   * @param id - The product ID
   * @returns Deletion confirmation
   * @throws NotFoundException if product not found
   */
  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({
    summary: 'Delete product',
    description: 'Permanently delete a product from the database',
  })
  @ApiParam({
    name: 'id',
    type: Number,
    description: 'The unique identifier of the product',
    example: 1,
  })
  @ApiResponse({
    status: HttpStatus.NO_CONTENT,
    description: 'Product deleted successfully',
  })
  @ApiNotFoundResponse({
    description: 'Product not found',
  })
  @ApiInternalServerErrorResponse({
    description: 'Internal server error',
  })
  async delete(@Param('id', ParseIntPipe) id: number) {
    const deleted = await this.productService.delete(id);
    if (!deleted) {
      throw new NotFoundException(`Product with ID ${id} not found`);
    }
    return { message: 'Product deleted successfully' };
  }
}
