import { Injectable } from '@nestjs/common';
import { BaseService } from '@nesvel/nestjs-orm';

import { Order } from '@order/entities/order.entity';

/**
 * Orderservice Service
 *
 * @description Service layer for Order entity business logic
 * @extends BaseService<Order>
 * @author Generated by @nesvel/nestjs-orm
 */
@Injectable()
export class OrderService extends BaseService<Order> {
  /**
   * Creates an instance of OrderService
   *
   * @param em - The EntityManager
   */
  // constructor(
  //   @InjectRepository(Order)
  //   private readonly orderRepository: EntityRepository<Order>
  // ) {
  //   // super(orderRepository);
  // }
  /**
   * Add custom service methods here
   *
   * @example
   * async findByEmail(email: string): Promise<Order | null> {
   *   return this.orderRepository.first({ email });
   * }
   *
   * @example
   * async activate(id: number): Promise<Order> {
   *   return this.orderRepository.update(id, { isActive: true });
   * }
   *
   * @example
   * async processBusinessLogic(data: Partial<Order>): Promise<Order> {
   *   // Complex business logic here
   *   const entity = await this.orderRepository.create(data);
   *   // Additional processing
   *   return entity;
   * }
   */
}
