import { Entity, Property, BaseEntity } from '@nesvel/nestjs-orm';

/**
 * Productentity Entity
 *
 * @description Generated model
 * @extends BaseEntity
 * @author Generated by @nesvel/nestjs-orm
 */
@Entity()
export class Productentity extends BaseEntity {
  /**
   * Name property
   */
  @Property()
  name!: string;

  /**
   * Add your custom properties here
   *
   * @example
   * @Property()
   * email!: string;
   *
   * @Property({ type: 'text', nullable: true })
   * description?: string;
   *
   * @Property({ default: true })
   * isActive!: boolean;
   */

  /**
   * Add relationships here
   *
   * @example
   * @ManyToOne(() => User)
   * user!: User;
   *
   * @OneToMany(() => Post, post => post.author)
   * posts = new Collection<Post>(this);
   */

  /**
   * Add custom methods here
   *
   * @example
   * getFullName(): string {
   *   return `${this.firstName} ${this.lastName}`;
   * }
   */
}
