/**
 * OrderStatus
 *
 * TypeScript enum for Generated enum
 *
 * @description OrderStatus enum definition
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```typescript
 * // Use in entity:
 * import { OrderStatus } from '@/enums/order-status.enum';
 *
 * @Entity()
 * export class MyEntity extends BaseEntity {
 *   @Property({ type: 'enum' })
 *   @Enum(() => OrderStatus)
 *   status: OrderStatus = OrderStatus.PLACEHOLDER;
 * }
 *
 * // Usage with static methods:
 * const allValues = OrderStatus.getValues();  // Get all enum values
 * const isValid = OrderStatus.isValid('active');  // Check if value is valid
 * const label = OrderStatus.getLabel(OrderStatus.PLACEHOLDER);  // Get display label
 * const found = OrderStatus.search('pend');  // Fuzzy search
 * const parsed = OrderStatus.parse('ACTIVE');  // Case-insensitive parse
 * ```
 */
export enum OrderStatus {
  /**
   * Placeholder value - replace with your actual enum values
   *
   * @example
   * // For a status enum:
   * // ACTIVE = 'active',
   * // INACTIVE = 'inactive',
   * // PENDING = 'pending',
   * // COMPLETED = 'completed',
   */
  PLACEHOLDER = 'placeholder',
}

/**
 * Get enum value labels for display
 *
 * Override this function to provide human-readable labels.
 * By default, returns the enum value as a string.
 *
 * @param value - Enum value
 * @returns Human-readable label
 *
 * @example
 * ```typescript
 * // Custom implementation:
 * export namespace OrderStatus {
 *   export function getLabel(value: OrderStatus): string {
 *     const labels: Record<OrderStatus, string> = {
 *       [OrderStatus.ACTIVE]: 'Active Status',
 *       [OrderStatus.INACTIVE]: 'Inactive Status',
 *     };
 *     return labels[value] || value;
 *   }
 * }
 *
 * // Usage:
 * const label = OrderStatus.getLabel(OrderStatus.ACTIVE);
 * // Returns: 'Active Status'
 * ```
 */
export function getLabel(value: OrderStatus): string {
  // TODO: Implement custom labels
  // Return the enum value as-is for now
  return value;
}

/**
 * Get all enum values as an array
 *
 * @returns Array of all enum values
 *
 * @example
 * ```typescript
 * const values = OrderStatus.getValues();
 * // Returns: ['value1', 'value2', ...]
 * ```
 */
export function getValues(): OrderStatus[] {
  return Object.values(OrderStatus).filter(
    (value): value is OrderStatus => typeof value === 'string'
  );
}

/**
 * Check if a value is a valid enum member
 *
 * @param value - Value to check
 * @returns True if value is valid enum member
 *
 * @example
 * ```typescript
 * if (OrderStatus.isValid('value1')) {
 *   // Value is valid
 * }
 * ```
 */
export function isValid(value: unknown): value is OrderStatus {
  return typeof value === 'string' && getValues().includes(value as OrderStatus);
}

/**
 * Get all enum entries as key-value pairs
 *
 * Useful for generating select options, dropdowns, or mapping displays.
 *
 * @returns Array of objects with key and value properties
 *
 * @example
 * ```typescript
 * const options = OrderStatus.getEntries();
 * // Returns: [{ key: 'KEY1', value: 'value1' }, { key: 'KEY2', value: 'value2' }]
 *
 * // Use in a select dropdown:
 * <select>
 *   {options.map(opt => (
 *     <option key={opt.key} value={opt.value}>
 *       {OrderStatus.getLabel(opt.value)}
 *     </option>
 *   ))}
 * </select>
 * ```
 */
export function getEntries(): Array<{ key: string; value: OrderStatus }> {
  return Object.entries(OrderStatus)
    .filter(([, value]) => typeof value === 'string')
    .map(([key, value]) => ({ key, value: value as OrderStatus }));
}

/**
 * Get enum keys as an array
 *
 * Returns the enum member names (not their values).
 *
 * @returns Array of enum keys
 *
 * @example
 * ```typescript
 * const keys = OrderStatus.getKeys();
 * // Returns: ['KEY1', 'KEY2', ...]
 * ```
 */
export function getKeys(): string[] {
  return Object.keys(OrderStatus).filter(
    (key) => typeof OrderStatus[key as keyof typeof OrderStatus] === 'string'
  );
}

/**
 * Convert enum value to human-readable format
 *
 * Transforms enum values to title case.
 * Useful for display purposes when custom labels aren't defined.
 *
 * @param value - Enum value to format
 * @returns Formatted string
 *
 * @example
 * ```typescript
 * // OrderStatus.toDisplayString('my_value') => 'My Value'
 * // OrderStatus.toDisplayString('my-value') => 'My Value'
 * // OrderStatus.toDisplayString('myvalue') => 'Myvalue'
 * ```
 */
export function toDisplayString(value: OrderStatus): string {
  return value
    .split(/[_-]/) // Split on underscore or hyphen
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
}

/**
 * Parse a string value to enum (case-insensitive)
 *
 * Safely converts string input to enum value, handling different cases.
 * Returns undefined if the value is invalid.
 *
 * @param value - String value to parse
 * @returns Enum value or undefined if invalid
 *
 * @example
 * ```typescript
 * OrderStatus.parse('VALUE1');   // Valid enum value
 * OrderStatus.parse('value1');   // Valid (case-insensitive)
 * OrderStatus.parse('VaLuE1');   // Valid (case-insensitive)
 * OrderStatus.parse('invalid');  // Returns: undefined
 * ```
 */
export function parse(value: string | null | undefined): OrderStatus | undefined {
  if (!value) return undefined;

  const normalized = value.toLowerCase();
  const found = getValues().find((enumValue) => enumValue.toLowerCase() === normalized);

  return found;
}

/**
 * Parse with fallback default value
 *
 * Like parse(), but returns a default value instead of undefined.
 *
 * @param value - String value to parse
 * @param defaultValue - Default enum value to return if parsing fails
 * @returns Enum value or the provided default
 *
 * @example
 * ```typescript
 * // If 'invalid' is not a valid enum value, returns the default
 * OrderStatus.parseOrDefault('invalid', OrderStatus.PLACEHOLDER);
 * // If 'value1' is valid, returns that value
 * OrderStatus.parseOrDefault('value1', OrderStatus.PLACEHOLDER);
 * ```
 */
export function parseOrDefault(
  value: string | null | undefined,
  defaultValue: OrderStatus
): OrderStatus {
  return parse(value) ?? defaultValue;
}

/**
 * Get enum value from partial match
 *
 * Finds the first enum value that includes the search string (case-insensitive).
 * Useful for fuzzy matching or search functionality.
 *
 * @param search - Search string
 * @returns First matching enum value or undefined
 *
 * @example
 * ```typescript
 * OrderStatus.search('val');  // Finds first value containing 'val'
 * OrderStatus.search('xyz');  // Returns: undefined if no match
 * ```
 */
export function search(searchStr: string): OrderStatus | undefined {
  if (!searchStr) return undefined;

  const normalized = searchStr.toLowerCase();
  return getValues().find((value) => value.toLowerCase().includes(normalized));
}

/**
 * Assert that a value is a valid enum member
 *
 * Throws an error if the value is not valid.
 * Useful for validating API inputs or user data.
 *
 * @param value - Value to assert
 * @param message - Optional custom error message
 * @returns The value if valid
 * @throws Error if value is not a valid enum member
 *
 * @example
 * ```typescript
 * try {
 *   OrderStatus.assertValid(userInput);
 *   // Value is valid, type is narrowed
 * } catch (error: Error | any) {
 *   console.error('Invalid value');
 * }
 * ```
 */
export function assertValid(value: unknown, message?: string): asserts value is OrderStatus {
  if (!isValid(value)) {
    throw new Error(
      message || `Invalid value: ${String(value)}. Valid values: ${getValues().join(', ')}`
    );
  }
}
