import { Command, CommandRunner, Option } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Schema Update Command
 *
 * Updates the database schema to match current entity definitions by generating
 * and executing ALTER TABLE statements. This command compares the existing
 * database schema with entity metadata and applies necessary changes.
 *
 * Use this command for:
 * - Syncing database with entity changes during development
 * - Applying schema updates without migrations
 * - Prototyping and rapid iteration
 * - Development environment schema evolution
 *
 * WARNING: This command can be destructive! It may:
 * - Drop columns that no longer exist in entities (data loss)
 * - Modify column types (potential data truncation)
 * - Remove indexes and constraints
 *
 * NEVER use in production! Use migrations instead for controlled changes.
 *
 * @description CLI command for updating database schema from entities
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```bash
 * # Update schema safely (won't drop columns/tables)
 * npm run console schema:update --safe
 *
 * # Update schema with all changes (DANGEROUS!)
 * npm run console schema:update
 *
 * # Dry run to see what would change
 * npm run console schema:update --dry-run
 * ```
 */
@Injectable()
@Command({
  name: 'schema:update',
  description: 'Update database schema to match entities',
})
export class SchemaUpdateCommand extends CommandRunner {
  private readonly logger = new Logger(SchemaUpdateCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  /**
   * Execute the schema:update command
   *
   * This method updates the database schema by:
   * 1. Comparing current schema with entity definitions
   * 2. Generating ALTER TABLE statements for differences
   * 3. Handling column additions, modifications, and deletions
   * 4. Updating indexes and constraints
   * 5. Executing changes in safe order
   *
   * Safe mode restrictions:
   * - Won't drop tables
   * - Won't drop columns
   * - Only adds new columns and indexes
   * - Safer for development use
   *
   * @param inputs - Command arguments
   * @param options - Command options (safe, dryRun, dropTables)
   * @returns Promise that resolves when schema is updated
   * @throws Error if schema update fails
   */
  async run(inputs: string[], options?: SchemaUpdateOptions): Promise<void> {
    try {
      const schemaGenerator = this.orm.getSchemaGenerator();

      // Warn about dangers
      if (!options?.safe && !options?.dryRun) {
        this.logger.warn('⚠️  WARNING: schema:update can cause data loss!');
        this.logger.warn('⚠️  Use --safe mode or --dry-run first to review changes');
        this.logger.warn('⚠️  For production, use migrations instead!\n');
      }

      if (options?.dryRun) {
        this.logger.log('DRY RUN MODE - Showing SQL that would be executed:\n');

        // Get the update SQL without executing
        const sql = await schemaGenerator.getUpdateSchemaSQL({
          safe: options?.safe ?? false,
          dropTables: options?.dropTables ?? true,
        });

        if (!sql || sql.trim().length === 0) {
          this.logger.log('✅ Schema is up to date - no changes needed');
          return;
        }

        this.logger.log('='.repeat(60));
        this.logger.log('UPDATE SCHEMA SQL:');
        this.logger.log('='.repeat(60));
        this.logger.log(sql);
        this.logger.log('='.repeat(60));

        this.logger.log('\n✅ Dry run complete - no changes made');
        return;
      }

      this.logger.log('Updating database schema...');

      // Update the schema
      await schemaGenerator.updateSchema({
        safe: options?.safe ?? false,
        dropTables: options?.dropTables ?? true,
      });

      this.logger.log('✅ Database schema updated successfully');

      if (options?.safe) {
        this.logger.log('\n📌 Safe mode was used - no tables or columns were dropped');
      }
    } catch (error: any) {
      this.logger.error('❌ Failed to update schema:', error.message);
      throw error;
    }
  }

  // @ts-ignore - nest-commander decorator signature mismatch
  @Option({
    flags: '--dry-run',
    description: 'Show SQL without executing',
  })
  parseDryRun(): boolean {
    return true;
  }

  // @ts-ignore - nest-commander decorator signature mismatch
  @Option({
    flags: '--safe',
    description: 'Safe mode - will not drop tables or columns',
  })
  parseSafe(): boolean {
    return true;
  }

  // @ts-ignore - nest-commander decorator signature mismatch
  @Option({
    flags: '--drop-tables',
    description: 'Allow dropping tables (default: true)',
  })
  parseDropTables(): boolean {
    return true;
  }
}

/**
 * Command options interface
 */
interface SchemaUpdateOptions {
  /** Show SQL without executing */
  dryRun?: boolean;
  /** Safe mode - won't drop tables or columns */
  safe?: boolean;
  /** Allow dropping tables */
  dropTables?: boolean;
}
