import { Command, CommandRunner, Option } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Schema Create Command
 *
 * Creates the database schema from entity definitions. This command generates
 * and executes DDL statements to create all tables, indexes, foreign keys,
 * and constraints defined in your MikroORM entities.
 *
 * Use this command for:
 * - Initial database setup from entity definitions
 * - Creating schema in new environments
 * - Development database initialization
 * - Testing environment setup
 * - Rapid prototyping with entity-first approach
 *
 * WARNING: This will fail if tables already exist. Use schema:update
 * for incremental changes or schema:drop + schema:create for a fresh start.
 *
 * @description CLI command for creating database schema from entities
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```bash
 * # Create database schema from entities
 * npm run console schema:create
 *
 * # Create with dry-run to see SQL without executing
 * npm run console schema:create --dry-run
 *
 * # Create and also generate migration file
 * npm run console schema:create --dump
 * ```
 */
@Injectable()
@Command({
  name: 'schema:create',
  description: 'Create database schema from entities',
})
export class SchemaCreateCommand extends CommandRunner {
  private readonly logger = new Logger(SchemaCreateCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  /**
   * Execute the schema:create command
   *
   * This method creates the complete database schema by:
   * 1. Analyzing all registered entity metadata
   * 2. Generating CREATE TABLE statements
   * 3. Generating CREATE INDEX statements
   * 4. Generating foreign key constraints
   * 5. Executing DDL in correct dependency order
   * 6. Verifying schema creation success
   *
   * The schema generator handles:
   * - Table creation with proper column types
   * - Primary and unique keys
   * - Indexes for performance
   * - Foreign key relationships
   * - Check constraints and defaults
   * - Database-specific optimizations
   *
   * @param inputs - Command arguments
   * @param options - Command options (dryRun, dump)
   * @returns Promise that resolves when schema is created
   * @throws Error if schema creation fails
   *
   * @example
   * ```typescript
   * // Generates SQL like:
   * // CREATE TABLE users (
   * //   id SERIAL PRIMARY KEY,
   * //   email VARCHAR(255) UNIQUE NOT NULL,
   * //   created_at TIMESTAMP DEFAULT NOW()
   * // );
   * ```
   */
  async run(inputs: string[], options?: SchemaCreateOptions): Promise<void> {
    try {
      const schemaGenerator = this.orm.getSchemaGenerator();

      if (options?.dryRun) {
        this.logger.log('DRY RUN MODE - Showing SQL that would be executed:\n');
        
        // Get the SQL without executing
        const sql = await schemaGenerator.getCreateSchemaSQL();
        
        this.logger.log('='.repeat(60));
        this.logger.log('CREATE SCHEMA SQL:');
        this.logger.log('='.repeat(60));
        this.logger.log(sql);
        this.logger.log('='.repeat(60));
        
        this.logger.log('\n✅ Dry run complete - no changes made');
        return;
      }

      this.logger.log('Creating database schema from entities...');

      // Create the schema
      await schemaGenerator.createSchema();

      this.logger.log('✅ Database schema created successfully');

      // Optionally dump the SQL to a file
      if (options?.dump) {
        this.logger.log('\nDumping schema SQL to file...');
        const sql = await schemaGenerator.getCreateSchemaSQL();
        // TODO: Implement SQL file generation
        this.logger.log('Schema SQL: (file generation not yet implemented)');
        this.logger.log(sql.substring(0, 500) + '...');
      }
    } catch (error: any) {
      this.logger.error('❌ Failed to create schema:', error.message);
      this.logger.error('\nCommon causes:');
      this.logger.error('- Tables already exist (use schema:drop first)');
      this.logger.error('- Database connection issues');
      this.logger.error('- Insufficient permissions');
      this.logger.error('- Invalid entity definitions');
      throw error;
    }
  }

  // @ts-ignore - nest-commander decorator signature mismatch
  @Option({
    flags: '--dry-run',
    description: 'Show SQL without executing',
  })
  parseDryRun(): boolean {
    return true;
  }

  // @ts-ignore - nest-commander decorator signature mismatch
  @Option({
    flags: '--dump',
    description: 'Dump SQL to migration file',
  })
  parseDump(): boolean {
    return true;
  }
}

/**
 * Command options interface
 */
interface SchemaCreateOptions {
  /** Show SQL without executing */
  dryRun?: boolean;
  /** Dump SQL to file */
  dump?: boolean;
}
