import { Command, CommandRunner } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Schema Validate Command
 *
 * Validates that the current database schema matches entity definitions.
 * This command compares the actual database structure with what your
 * entities expect and reports any discrepancies.
 *
 * Validation checks:
 * - Missing tables or columns
 * - Incorrect column types
 * - Missing indexes
 * - Foreign key mismatches
 * - Constraint differences
 * - Orphaned database objects
 *
 * Use this command for:
 * - Verifying schema integrity
 * - Checking if migrations are needed
 * - CI/CD validation steps
 * - Troubleshooting entity-database mismatches
 * - Pre-deployment checks
 *
 * @description CLI command for validating database schema against entities
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 *
 * @example
 * ```bash
 * # Validate current database schema
 * npm run console schema:validate
 *
 * # Output shows any discrepancies found
 * ```
 */
@Injectable()
@Command({
  name: 'schema:validate',
  description: 'Validate database schema matches entities',
})
export class SchemaValidateCommand extends CommandRunner {
  private readonly logger = new Logger(SchemaValidateCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  /**
   * Execute the schema:validate command
   *
   * This method validates the schema by:
   * 1. Loading current database schema metadata
   * 2. Comparing with entity definitions
   * 3. Identifying discrepancies
   * 4. Reporting missing or extra objects
   * 5. Suggesting corrective actions
   *
   * Validation results include:
   * - List of schema differences
   * - Severity of each issue
   * - SQL statements to fix issues
   * - Recommendations for next steps
   *
   * @param inputs - Command arguments (not used)
   * @returns Promise that resolves when validation is complete
   * @throws Error if validation cannot be performed
   *
   * @example
   * ```typescript
   * // Output example:
   * // ✅ Schema validation passed
   * // OR
   * // ❌ Schema validation failed:
   * // - Missing column: users.phone_number
   * // - Type mismatch: posts.views (expected: integer, found: varchar)
   * // - Missing index: idx_users_email
   * ```
   */
  async run(): Promise<void> {
    try {
      this.logger.log('Validating database schema...\n');

      const schemaGenerator = this.orm.getSchemaGenerator();

      // Get the SQL that would be needed to sync schema
      const updateSQL = await schemaGenerator.getUpdateSchemaSQL({ safe: false });

      if (!updateSQL || updateSQL.trim().length === 0) {
        this.logger.log('✅ Schema validation passed');
        this.logger.log('✅ Database schema matches entity definitions');
        return;
      }

      // Schema has differences
      this.logger.error('❌ Schema validation failed');
      this.logger.error('❌ Database schema does NOT match entity definitions\n');

      this.logger.log('Schema differences found:');
      this.logger.log('='.repeat(60));
      this.logger.log(updateSQL);
      this.logger.log('='.repeat(60));

      this.logger.log('\n📋 Recommended actions:');
      this.logger.log('1. Review the SQL statements above');
      this.logger.log('2. Create a migration: npm run console make:migration SyncSchema');
      this.logger.log('3. Run migrations: npm run console migrate');
      this.logger.log('4. OR use schema:update for development (CAUTION!)');

      // Exit with error code
      process.exit(1);
    } catch (error: any) {
      this.logger.error('❌ Failed to validate schema:', error.message);
      throw error;
    }
  }
}
