import * as fs from 'fs';
import * as path from 'path';
import { Command } from 'nest-commander';
import { BaseMakeCommand } from '../base-make.command';
/**
 * Make TSConfig Command
 *
 * Generates a tsconfig.json file with path aliases configured for the project.
 * The generated config extends @nesvel/typescript-config/nest and includes
 * common path aliases for better import organization.
 *
 * @description CLI command for generating tsconfig.json
 * @author Generated by @nesvel/nestjs-console
 *
 * @example
 * ```bash
 * # Generate tsconfig.json in project root
 * npm run console make:tsconfig
 * ```
 */
@Command({
  name: 'make:tsconfig',
  description: 'Create a tsconfig.json with path aliases',
})
export class MakeTsconfigCommand extends BaseMakeCommand {
  /**
   * Execute the make:tsconfig command
   *
   * @returns Promise that resolves when the tsconfig.json file is created
   */
  async run(): Promise<void> {
    const projectRoot = this.findProjectRoot();
    const tsconfigPath = path.join(projectRoot, 'tsconfig.json');

    // Check if tsconfig.json already exists
    if (fs.existsSync(tsconfigPath)) {
      throw new Error('tsconfig.json already exists. Please remove it first or edit it manually.');
    }

    // Read the stub template
    const stubPath = path.join(this.stubsPath, 'tsconfig.stub.ejs');

    if (!fs.existsSync(stubPath)) {
      throw new Error(`Stub file not found: ${stubPath}`);
    }

    const stubContent = fs.readFileSync(stubPath, 'utf-8');

    // Write the tsconfig.json file
    fs.writeFileSync(tsconfigPath, stubContent);

    console.log(`✓ Created tsconfig.json: ${tsconfigPath}`);
  }
}
