import { Command } from 'nest-commander';
import { BaseMakeCommand } from '../base-make.command';

/**
 * Make Command Command
 *
 * Generates a new CLI command class that extends BaseMakeCommand.
 * The generated command can be used to create custom make commands.
 *
 * @description CLI command for generating custom command classes
 * @author Generated by @nesvel/nestjs-console
 *
 * @example
 * ```bash
 * # Generate a MakeController command
 * npm run console make:command MakeController
 *
 * # Generate a MakeService command
 * npm run console make:command MakeService
 * ```
 */
@Command({
  name: 'make:command',
  arguments: '<name>',
  description: 'Create a new custom CLI command',
})
export class MakeCommandCommand extends BaseMakeCommand {
  /**
   * Execute the make:command command
   *
   * @param inputs - Command arguments [name]
   * @returns Promise that resolves when the command file is created
   */
  async run(inputs: string[]): Promise<void> {
    const [name] = inputs;

    // Validate that name argument was provided
    if (!name) {
      throw new Error('Command name argument is required.');
    }

    // Convert name to PascalCase for class name
    const className = this.toClassName(name);

    // Extract command name from class name (remove 'Command' suffix if present)
    let commandName = name.replace(/Command$/i, '');
    commandName = this.toFileName(commandName);

    // Default stub and output settings
    const stubName = 'model'; // Default stub for generated files
    const outputDir = 'src/generated';

    // Generate file from EJS template
    await this.generateFromStub(
      name,
      {
        stubName: 'command',
        outputDir: 'src/commands',
        suffix: 'command',
      },
      {
        commandName,
        stubName,
        outputDir,
        description: `Generate ${className}`,
      }
    );
  }
}
