import { Command, Group } from '@nesvel/nestjs-console';
import { CommandRunner } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Database Show Command
 *
 * Displays comprehensive database information including connection details,
 * statistics, and configuration.
 *
 * @description CLI command for showing database information
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 */
@Injectable()
@Command({
  name: 'db:show',
  description: 'Display database information',
})
@Group('Database Inspection')
export class DbShowCommand extends CommandRunner {
  private readonly logger = new Logger(DbShowCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  async run(): Promise<void> {
    try {
      this.logger.log('Database Information:\n');

      const config = this.orm.config;
      const connection = this.orm.em.getConnection();

      this.logger.log('='.repeat(60));
      this.logger.log(`Driver: ${config.get('type' as any)}`);
      this.logger.log(`Database: ${config.get('dbName')}`);
      this.logger.log(`Host: ${config.get('host')}:${config.get('port')}`);
      this.logger.log('='.repeat(60));

      // Get table count
      const metadata = this.orm.getMetadata();
      const entities = metadata.getAll();
      this.logger.log(`\nRegistered Entities: ${entities.size}`);

      // Test connection
      try {
        await connection.execute('SELECT 1');
        this.logger.log('Connection Status: ✅ Connected');
      } catch {
        this.logger.log('Connection Status: ❌ Disconnected');
      }

      this.logger.log('\n✅ Database information displayed');
    } catch (error: any) {
      this.logger.error('❌ Failed to show database info:', error.message);
      throw error;
    }
  }
}
