import { Command, CommandRunner } from 'nest-commander';
import { MikroORM } from '@mikro-orm/core';
import { Injectable, Logger } from '@nestjs/common';

/**
 * Database Table Command  
 *
 * Shows detailed structure of a specific database table including columns,
 * types, indexes, and constraints.
 *
 * @description CLI command for inspecting table structure
 * @author Generated by @nesvel/nestjs-orm
 * @since 1.0.0
 */
@Injectable()
@Command({
  name: 'db:table',
  arguments: '<name>',
  description: 'Show table structure',
})
export class DbTableCommand extends CommandRunner {
  private readonly logger = new Logger(DbTableCommand.name);

  constructor(private readonly orm: MikroORM) {
    super();
  }

  async run(inputs: string[]): Promise<void> {
    try {
      const [tableName] = inputs;

      if (!tableName) {
        throw new Error('Table name is required');
      }

      this.logger.log(`Table Structure: ${tableName}\n`);

      const connection = this.orm.em.getConnection();
      
      // Get table info (database-specific query)
      // This is a simplified version - should be adapted per database type
      const result = await connection.execute(
        `SELECT column_name, data_type, is_nullable 
         FROM information_schema.columns 
         WHERE table_name = ?`,
        [tableName]
      );

      if (!result || result.length === 0) {
        this.logger.error(`❌ Table "${tableName}" not found`);
        return;
      }

      this.logger.log('='.repeat(80));
      this.logger.log('Column Name'.padEnd(30) + 'Type'.padEnd(30) + 'Nullable');
      this.logger.log('='.repeat(80));

      result.forEach((row: any) => {
        this.logger.log(
          row.column_name.padEnd(30) +
          row.data_type.padEnd(30) +
          row.is_nullable
        );
      });

      this.logger.log('='.repeat(80));
      this.logger.log(`\n✅ Table structure displayed`);
    } catch (error: any) {
      this.logger.error('❌ Failed to show table:', error.message);
      throw error;
    }
  }
}
