import { Module } from '@nestjs/common';
import { OrmModule } from '@nesvel/nestjs-orm';

import { Order } from '@order/entities/order.entity';
import { OrderService } from '@order/services/order.service';
import { OrderSubscriber } from './subscribers/order.subscriber';
import { OrderController } from '@order/controllers/order.controller';

/**
 * OrderModule Module
 *
 * @description Module for Order feature
 * @author Generated by @nesvel/nestjs-orm
 */
@Module({
  /**
   * Module imports
   * Register <%= modelName %> entity with OrmModule
   */
  imports: [OrmModule.forFeature([Order])],

  /**
   * Controllers
   * Handle HTTP requests for <%= modelName.toLowerCase() %> resources
   */
  controllers: [OrderController],

  /**
   * Providers
   * Service layer and repository for <%= modelName %> business logic
   */
  providers: [OrderService, OrderSubscriber],

  /**
   * Exports
   * Make <%= serviceName %> available to other modules
   */
  exports: [OrderService],
})
export class OrderModule {}
